/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cgp/Develop/hexe/nimcache/sdl1_sdl_ttf.o /home/cgp/Develop/hexe/nimcache/sdl1_sdl_ttf.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Version_TUGH4P4jGdNVTX5QSaf8Uw Version_TUGH4P4jGdNVTX5QSaf8Uw;
typedef struct Font_ULt9a5WgPpEtuhHebN5GvSw Font_ULt9a5WgPpEtuhHebN5GvSw;
typedef struct Rwops_X9aV6NIIXl81VrKmMNXaaIA Rwops_X9aV6NIIXl81VrKmMNXaaIA;
typedef struct Surface_bFoWQ9a1fqAJG6BOtYsYY2g Surface_bFoWQ9a1fqAJG6BOtYsYY2g;
typedef struct Color_9apUnnwImZA9bub3LK9aEySmA Color_9apUnnwImZA9bub3LK9aEySmA;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Mem_xc0JihOF1AAH9ckCbD8GqXw Mem_xc0JihOF1AAH9ckCbD8GqXw;
typedef struct Pixelformat_YOl3D8kldv22sO4atKEvDA Pixelformat_YOl3D8kldv22sO4atKEvDA;
typedef struct Rect_Y0FvJAkVbcX1wgIBeWhLOg Rect_Y0FvJAkVbcX1wgIBeWhLOg;
typedef struct Palette_r4iaLWv4Ancf4wpNWuLTXg Palette_r4iaLWv4Ancf4wpNWuLTXg;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(Version_TUGH4P4jGdNVTX5QSaf8Uw*, TY_9bm3w5QaUTEyyRhl0bG6ATA) (void);
typedef N_CDECL_PTR(void, TY_NuisSWKwsQg36a0Egqo6Qw) (int swapped0);
typedef N_CDECL_PTR(int, TY_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(Font_ULt9a5WgPpEtuhHebN5GvSw*, TY_S4eGMxL9brpbPBgDf0PMh3g) (NCSTRING filename0, int ptsize0);
typedef N_CDECL_PTR(Font_ULt9a5WgPpEtuhHebN5GvSw*, TY_KtDG9aWxQjiHu5Q9aQP6i1QQ) (NCSTRING filename0, int ptsize0, NI32 index0);
typedef N_CDECL_PTR(Font_ULt9a5WgPpEtuhHebN5GvSw*, TY_vYcclt4VxCpvAbPuw65FpA) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* src0, int freesrc0, int ptsize0);
typedef N_CDECL_PTR(Font_ULt9a5WgPpEtuhHebN5GvSw*, TY_PkL0zVeZvskOJQGjj1ZvBQ) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* src0, int freesrc0, int ptsize0, NI32 index0);
typedef N_CDECL_PTR(int, TY_Hehk9a2BvTEkHZesOzr5Urw) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0);
typedef N_CDECL_PTR(void, TY_DHi6wcRweGMHBy6Dkvyl9aQ) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, int style0);
typedef N_CDECL_PTR(NI32, TY_Qhvzp9aMOQXW2WPPVFjgRVg) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0);
typedef N_CDECL_PTR(NCSTRING, TY_bRE9cn6CuDeZ9cXG7gIBPpMA) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0);
typedef N_CDECL_PTR(int, TY_P7jVKUXS8O6j2CBm0Z9abuA) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16 ch0, int* minx0, int* maxx0, int* miny0, int* maxy0, int* advance0);
typedef N_CDECL_PTR(int, TY_E9aYrNGg1kXZoj1Oi1yMTKg) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NCSTRING text0, int* w0, int* y0);
typedef N_CDECL_PTR(int, TY_PN8nRZmb9cey9boXNqfHOTJA) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16* text0, int* w0, int* y0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_mMl69afXl2IJ0MjSzxeg9a9aQ) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NCSTRING text0, Color_9apUnnwImZA9bub3LK9aEySmA fg0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_LrDPeaztHAS6zUYfc9ab9ceg) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16* text0, Color_9apUnnwImZA9bub3LK9aEySmA fg0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_7w0rUQ9a2EBY66E4gPj8OBQ) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16 ch0, Color_9apUnnwImZA9bub3LK9aEySmA fg0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_fKB4B9cjHK5fVeZVH4EfMug) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NCSTRING text0, Color_9apUnnwImZA9bub3LK9aEySmA fg0, Color_9apUnnwImZA9bub3LK9aEySmA bg0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_DL79bMcERYzPpQvkSYe9bb3w) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16* text0, Color_9apUnnwImZA9bub3LK9aEySmA fg0, Color_9apUnnwImZA9bub3LK9aEySmA bg0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_6CX6b0igZ1QLl4dqSGr8uQ) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0, NU16 ch0, Color_9apUnnwImZA9bub3LK9aEySmA fg0, Color_9apUnnwImZA9bub3LK9aEySmA bg0);
typedef N_CDECL_PTR(void, TY_9bZcwskf9ayOKbXmTr9bTZdAQ) (Font_ULt9a5WgPpEtuhHebN5GvSw* font0);
typedef N_CDECL_PTR(void, TY_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct  Version_TUGH4P4jGdNVTX5QSaf8Uw  {
NU8 major;
NU8 minor;
NU8 patch;
};
struct  Font_ULt9a5WgPpEtuhHebN5GvSw  {
char dummy;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_CDECL_PTR(NI, TY_XW1wO2i70wfDcQe1kgU4yg) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0, NI offset0, NI whence0);
typedef N_CDECL_PTR(NI, TY_wWpNNMZcwVz9c54wldudHbQ) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0, void* theptr0, NI size0, NI maxnum0);
typedef N_CDECL_PTR(NI, TY_BEGnXwJkELqHe1cSnttoGQ) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0);
struct  Mem_xc0JihOF1AAH9ckCbD8GqXw  {
NU8* base;
NU8* here;
NU8* stop;
};
struct  Rwops_X9aV6NIIXl81VrKmMNXaaIA  {
TY_XW1wO2i70wfDcQe1kgU4yg seek;
TY_wWpNNMZcwVz9c54wldudHbQ read;
TY_wWpNNMZcwVz9c54wldudHbQ write;
TY_BEGnXwJkELqHe1cSnttoGQ closefile;
int thetype;
Mem_xc0JihOF1AAH9ckCbD8GqXw mem;
};
struct  Rect_Y0FvJAkVbcX1wgIBeWhLOg  {
NI16 x;
NI16 y;
NU16 w;
NU16 h;
};
struct  Surface_bFoWQ9a1fqAJG6BOtYsYY2g  {
NI32 flags;
Pixelformat_YOl3D8kldv22sO4atKEvDA* format;
int w;
int h;
NU16 pitch;
void* pixels;
int offset;
void* hwdata;
Rect_Y0FvJAkVbcX1wgIBeWhLOg cliprect;
NI32 unused1;
NI32 locked;
void* blitmap;
int formatversion;
int refcount;
};
struct  Color_9apUnnwImZA9bub3LK9aEySmA  {
NU8 r;
NU8 g;
NU8 b;
NU8 unused;
};
struct  Pixelformat_YOl3D8kldv22sO4atKEvDA  {
Palette_r4iaLWv4Ancf4wpNWuLTXg* palette;
NU8 bitsperpixel;
NU8 bytesperpixel;
NU8 rloss;
NU8 gloss;
NU8 bloss;
NU8 aloss;
NU8 rshift;
NU8 gshift;
NU8 bshift;
NU8 ashift;
NI32 rmask;
NI32 gmask;
NI32 bmask;
NI32 amask;
NI32 colorkey;
NU8 alpha;
};
struct  Palette_r4iaLWv4Ancf4wpNWuLTXg  {
NI ncolors;
Color_9apUnnwImZA9bub3LK9aEySmA* colors;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
N_NIMCALL(void, version_e5iGqRZBtcLwRY7u7pzPSQ)(Version_TUGH4P4jGdNVTX5QSaf8Uw* x0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* T_Fl6LJMic9a29aOwQ8qXgtiMA_2;
TY_9bm3w5QaUTEyyRhl0bG6ATA Dl_124219;
TY_NuisSWKwsQg36a0Egqo6Qw Dl_124222;
TY_cez8YhJI0vaCUcjGg6z4zA Dl_124225;
TY_S4eGMxL9brpbPBgDf0PMh3g Dl_124227;
TY_KtDG9aWxQjiHu5Q9aQP6i1QQ Dl_124231;
TY_vYcclt4VxCpvAbPuw65FpA Dl_124236;
TY_PkL0zVeZvskOJQGjj1ZvBQ Dl_124241;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124247;
TY_DHi6wcRweGMHBy6Dkvyl9aQ Dl_124250;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124254;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124257;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124260;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124263;
TY_Qhvzp9aMOQXW2WPPVFjgRVg Dl_124266;
TY_Hehk9a2BvTEkHZesOzr5Urw Dl_124269;
TY_bRE9cn6CuDeZ9cXG7gIBPpMA Dl_124272;
TY_bRE9cn6CuDeZ9cXG7gIBPpMA Dl_124275;
TY_P7jVKUXS8O6j2CBm0Z9abuA Dl_124278;
TY_E9aYrNGg1kXZoj1Oi1yMTKg Dl_124292;
TY_E9aYrNGg1kXZoj1Oi1yMTKg Dl_124300;
TY_PN8nRZmb9cey9boXNqfHOTJA Dl_124308;
TY_mMl69afXl2IJ0MjSzxeg9a9aQ Dl_124316;
TY_LrDPeaztHAS6zUYfc9ab9ceg Dl_124321;
TY_7w0rUQ9a2EBY66E4gPj8OBQ Dl_124326;
TY_fKB4B9cjHK5fVeZVH4EfMug Dl_124331;
TY_fKB4B9cjHK5fVeZVH4EfMug Dl_124337;
TY_DL79bMcERYzPpQvkSYe9bb3w Dl_124343;
TY_6CX6b0igZ1QLl4dqSGr8uQ Dl_124349;
TY_mMl69afXl2IJ0MjSzxeg9a9aQ Dl_124355;
TY_mMl69afXl2IJ0MjSzxeg9a9aQ Dl_124360;
TY_LrDPeaztHAS6zUYfc9ab9ceg Dl_124365;
TY_7w0rUQ9a2EBY66E4gPj8OBQ Dl_124370;
TY_9bZcwskf9ayOKbXmTr9bTZdAQ Dl_124375;
TY_ln4kdL5W9bbX4a1xl8nnVXQ Dl_124378;
TY_cez8YhJI0vaCUcjGg6z4zA Dl_124380;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_mMl69afXl2IJ0MjSzxeg9a9aQ Dl_124387;
TNimType NTI_ULt9a5WgPpEtuhHebN5GvSw;
TNimType NTI_eu769bCPokwXQmYUXtNioLw;
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_4, "libSDL_ttf.so", 13);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_6, "libSDL_ttf.so.1", 15);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_8, "libSDL_ttf.so.0", 15);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_10, "libSDL_ttf-2.0.so", 17);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_12, "libSDL_ttf-2.0.so.1", 19);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_14, "libSDL_ttf-2.0.so.0", 19);
STRING_LITERAL(T_Fl6LJMic9a29aOwQ8qXgtiMA_15, "libSDL_ttf(|-2.0).so(|.1|.0)", 28);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(void, version_e5iGqRZBtcLwRY7u7pzPSQ)(Version_TUGH4P4jGdNVTX5QSaf8Uw* x0) {
	nimfr("version", "sdl_ttf.nim")
	nimln(187, "sdl_ttf.nim");
	(*x0).major = ((NU8) 2);
	nimln(188, "sdl_ttf.nim");
	(*x0).minor = ((NU8) 0);
	nimln(189, "sdl_ttf.nim");
	(*x0).patch = ((NU8) 8);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, sdl1_sdl_ttfInit000)(void) {
	nimfr("sdl_ttf", "sdl_ttf.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl1_sdl_ttfDatInit000)(void) {
static TNimNode T_Fl6LJMic9a29aOwQ8qXgtiMA_0[1];
NTI_ULt9a5WgPpEtuhHebN5GvSw.size = sizeof(Font_ULt9a5WgPpEtuhHebN5GvSw);
NTI_ULt9a5WgPpEtuhHebN5GvSw.kind = 18;
NTI_ULt9a5WgPpEtuhHebN5GvSw.base = 0;
NTI_ULt9a5WgPpEtuhHebN5GvSw.flags = 3;
T_Fl6LJMic9a29aOwQ8qXgtiMA_0[0].len = 0; T_Fl6LJMic9a29aOwQ8qXgtiMA_0[0].kind = 2;
NTI_ULt9a5WgPpEtuhHebN5GvSw.node = &T_Fl6LJMic9a29aOwQ8qXgtiMA_0[0];
NTI_eu769bCPokwXQmYUXtNioLw.size = sizeof(Font_ULt9a5WgPpEtuhHebN5GvSw*);
NTI_eu769bCPokwXQmYUXtNioLw.kind = 21;
NTI_eu769bCPokwXQmYUXtNioLw.base = (&NTI_ULt9a5WgPpEtuhHebN5GvSw);
NTI_eu769bCPokwXQmYUXtNioLw.flags = 3;
if (!((T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_4))
||(T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_6))
||(T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_8))
||(T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_10))
||(T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_12))
||(T_Fl6LJMic9a29aOwQ8qXgtiMA_2 = nimLoadLibrary((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_14))
)) nimLoadLibraryError((NimStringDesc*) &T_Fl6LJMic9a29aOwQ8qXgtiMA_15);
	Dl_124219 = (TY_9bm3w5QaUTEyyRhl0bG6ATA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_Linked_Version");
	Dl_124222 = (TY_NuisSWKwsQg36a0Egqo6Qw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_ByteSwappedUNICODE");
	Dl_124225 = (TY_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_Init");
	Dl_124227 = (TY_S4eGMxL9brpbPBgDf0PMh3g) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_OpenFont");
	Dl_124231 = (TY_KtDG9aWxQjiHu5Q9aQP6i1QQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_OpenFontIndex");
	Dl_124236 = (TY_vYcclt4VxCpvAbPuw65FpA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_OpenFontRW");
	Dl_124241 = (TY_PkL0zVeZvskOJQGjj1ZvBQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_OpenFontIndexRW");
	Dl_124247 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_GetFontStyle");
	Dl_124250 = (TY_DHi6wcRweGMHBy6Dkvyl9aQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_SetFontStyle");
	Dl_124254 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontHeight");
	Dl_124257 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontAscent");
	Dl_124260 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontDescent");
	Dl_124263 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontLineSkip");
	Dl_124266 = (TY_Qhvzp9aMOQXW2WPPVFjgRVg) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontFaces");
	Dl_124269 = (TY_Hehk9a2BvTEkHZesOzr5Urw) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontFaceIsFixedWidth");
	Dl_124272 = (TY_bRE9cn6CuDeZ9cXG7gIBPpMA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontFaceFamilyName");
	Dl_124275 = (TY_bRE9cn6CuDeZ9cXG7gIBPpMA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_FontFaceStyleName");
	Dl_124278 = (TY_P7jVKUXS8O6j2CBm0Z9abuA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_GlyphMetrics");
	Dl_124292 = (TY_E9aYrNGg1kXZoj1Oi1yMTKg) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_SizeText");
	Dl_124300 = (TY_E9aYrNGg1kXZoj1Oi1yMTKg) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_SizeUTF8");
	Dl_124308 = (TY_PN8nRZmb9cey9boXNqfHOTJA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_SizeUNICODE");
	Dl_124316 = (TY_mMl69afXl2IJ0MjSzxeg9a9aQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUTF8_Solid");
	Dl_124321 = (TY_LrDPeaztHAS6zUYfc9ab9ceg) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUNICODE_Solid");
	Dl_124326 = (TY_7w0rUQ9a2EBY66E4gPj8OBQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderGlyph_Solid");
	Dl_124331 = (TY_fKB4B9cjHK5fVeZVH4EfMug) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderText_Shaded");
	Dl_124337 = (TY_fKB4B9cjHK5fVeZVH4EfMug) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUTF8_Shaded");
	Dl_124343 = (TY_DL79bMcERYzPpQvkSYe9bb3w) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUNICODE_Shaded");
	Dl_124349 = (TY_6CX6b0igZ1QLl4dqSGr8uQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderGlyph_Shaded");
	Dl_124355 = (TY_mMl69afXl2IJ0MjSzxeg9a9aQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderText_Blended");
	Dl_124360 = (TY_mMl69afXl2IJ0MjSzxeg9a9aQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUTF8_Blended");
	Dl_124365 = (TY_LrDPeaztHAS6zUYfc9ab9ceg) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderUNICODE_Blended");
	Dl_124370 = (TY_7w0rUQ9a2EBY66E4gPj8OBQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderGlyph_Blended");
	Dl_124375 = (TY_9bZcwskf9ayOKbXmTr9bTZdAQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_CloseFont");
	Dl_124378 = (TY_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_Quit");
	Dl_124380 = (TY_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_WasInit");
	Dl_124387 = (TY_mMl69afXl2IJ0MjSzxeg9a9aQ) nimGetProcAddr(T_Fl6LJMic9a29aOwQ8qXgtiMA_2, "TTF_RenderText_Solid");
}

