/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cgp/Develop/hexe/nimcache/sdl1_sdl.o /home/cgp/Develop/hexe/nimcache/sdl1_sdl.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#undef linux
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
typedef struct Pixelformat_YOl3D8kldv22sO4atKEvDA Pixelformat_YOl3D8kldv22sO4atKEvDA;
typedef struct Surface_bFoWQ9a1fqAJG6BOtYsYY2g Surface_bFoWQ9a1fqAJG6BOtYsYY2g;
typedef struct Rect_Y0FvJAkVbcX1wgIBeWhLOg Rect_Y0FvJAkVbcX1wgIBeWhLOg;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Palette_r4iaLWv4Ancf4wpNWuLTXg Palette_r4iaLWv4Ancf4wpNWuLTXg;
typedef struct Color_9apUnnwImZA9bub3LK9aEySmA Color_9apUnnwImZA9bub3LK9aEySmA;
typedef struct Rwops_X9aV6NIIXl81VrKmMNXaaIA Rwops_X9aV6NIIXl81VrKmMNXaaIA;
typedef struct Mem_xc0JihOF1AAH9ckCbD8GqXw Mem_xc0JihOF1AAH9ckCbD8GqXw;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(NI32, TY_CXl344VSAMaA2Bw9bCvgXcA) (Pixelformat_YOl3D8kldv22sO4atKEvDA* format0, NU8 r0, NU8 g0, NU8 b0, NU8 a0);
typedef N_CDECL_PTR(NCSTRING, TY_09bvyvHFtWbkzL5AHgf0bKw) (void);
typedef N_CDECL_PTR(void, TY_2eKqBOvpeTZKPUWu5YiExA) (Surface_bFoWQ9a1fqAJG6BOtYsYY2g* surface0);
struct  Rect_Y0FvJAkVbcX1wgIBeWhLOg  {
NI16 x;
NI16 y;
NU16 w;
NU16 h;
};
struct  Surface_bFoWQ9a1fqAJG6BOtYsYY2g  {
NI32 flags;
Pixelformat_YOl3D8kldv22sO4atKEvDA* format;
int w;
int h;
NU16 pitch;
void* pixels;
int offset;
void* hwdata;
Rect_Y0FvJAkVbcX1wgIBeWhLOg cliprect;
NI32 unused1;
NI32 locked;
void* blitmap;
int formatversion;
int refcount;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Pixelformat_YOl3D8kldv22sO4atKEvDA  {
Palette_r4iaLWv4Ancf4wpNWuLTXg* palette;
NU8 bitsperpixel;
NU8 bytesperpixel;
NU8 rloss;
NU8 gloss;
NU8 bloss;
NU8 aloss;
NU8 rshift;
NU8 gshift;
NU8 bshift;
NU8 ashift;
NI32 rmask;
NI32 gmask;
NI32 bmask;
NI32 amask;
NI32 colorkey;
NU8 alpha;
};
struct  Palette_r4iaLWv4Ancf4wpNWuLTXg  {
NI ncolors;
Color_9apUnnwImZA9bub3LK9aEySmA* colors;
};
struct  Color_9apUnnwImZA9bub3LK9aEySmA  {
NU8 r;
NU8 g;
NU8 b;
NU8 unused;
};
typedef Color_9apUnnwImZA9bub3LK9aEySmA TY_5KyVnex9bkoLNM2672VMzKg[65001];
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_wc33gX9cDmCWKwjWAU0IECw) (NI32 flags0, NI width0, NI height0, NI depth0, NI32 rmask0, NI32 gmask0, NI32 bmask0, NI32 amask0);
typedef N_CDECL_PTR(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*, TY_PTBY7HwZryF5ZlXLhiuE9cw) (NI width0, NI height0, NI bpp0, NU32 flags0);
typedef N_CDECL_PTR(NI, TY_PGLFr4n9aRBWHFAO4t6jqJA) (Surface_bFoWQ9a1fqAJG6BOtYsYY2g* surface0, Rwops_X9aV6NIIXl81VrKmMNXaaIA* dst0, NI freedst0);
typedef N_CDECL_PTR(Rwops_X9aV6NIIXl81VrKmMNXaaIA*, TY_LmiM0IShxJ1VYR39as6EpeA) (NCSTRING filename0, NCSTRING mode0);
typedef N_CDECL_PTR(NI, TY_sWlGqWNnw8S4mvjxAn82Og) (Surface_bFoWQ9a1fqAJG6BOtYsYY2g* src0, Rect_Y0FvJAkVbcX1wgIBeWhLOg* srcrect0, Surface_bFoWQ9a1fqAJG6BOtYsYY2g* dst0, Rect_Y0FvJAkVbcX1wgIBeWhLOg* dstrect0);
typedef N_CDECL_PTR(NI, TY_5dgUv4jBqbFWzIpnzViqjQ) (Surface_bFoWQ9a1fqAJG6BOtYsYY2g* dst0, Rect_Y0FvJAkVbcX1wgIBeWhLOg* dstrect0, NI32 color0);
typedef N_CDECL_PTR(NI, TY_L3aEu9cc4nB9a9cl7KrgxeZAg) (NI32 flags0);
typedef N_CDECL_PTR(NI, TY_XW1wO2i70wfDcQe1kgU4yg) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0, NI offset0, NI whence0);
typedef N_CDECL_PTR(NI, TY_wWpNNMZcwVz9c54wldudHbQ) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0, void* theptr0, NI size0, NI maxnum0);
typedef N_CDECL_PTR(NI, TY_BEGnXwJkELqHe1cSnttoGQ) (Rwops_X9aV6NIIXl81VrKmMNXaaIA* context0);
struct  Mem_xc0JihOF1AAH9ckCbD8GqXw  {
NU8* base;
NU8* here;
NU8* stop;
};
struct  Rwops_X9aV6NIIXl81VrKmMNXaaIA  {
TY_XW1wO2i70wfDcQe1kgU4yg seek;
TY_wWpNNMZcwVz9c54wldudHbQ read;
TY_wWpNNMZcwVz9c54wldudHbQ write;
TY_BEGnXwJkELqHe1cSnttoGQ closefile;
int thetype;
Mem_xc0JihOF1AAH9ckCbD8GqXw mem;
};
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path0);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path0);
N_NIMCALL(void*, nimGetProcAddr)(void* lib0, NCSTRING name0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* T_jd6ZfJ12PtMN0qL7SizLLQ_2;
TY_CXl344VSAMaA2Bw9bCvgXcA Dl_123342;
TY_09bvyvHFtWbkzL5AHgf0bKw Dl_122804;
TY_2eKqBOvpeTZKPUWu5YiExA Dl_123402;
TNimType NTI_bFoWQ9a1fqAJG6BOtYsYY2g;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA;
TNimType NTI_YOl3D8kldv22sO4atKEvDA;
TNimType NTI_r4iaLWv4Ancf4wpNWuLTXg;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA;
TNimType NTI_9apUnnwImZA9bub3LK9aEySmA;
extern TNimType NTI_k3HXouOuhqAKq0dx450lXQ;
TNimType NTI_5KyVnex9bkoLNM2672VMzKg;
TNimType NTI_XBOgL4UKEgU7QdulJrhJkQ;
TNimType NTI_eosgyp0pX9aYfPHui6dCIHw;
TNimType NTI_APtBDKdndih08ga9baTCQnQ;
extern TNimType NTI_nlCscttRCss70IBTyuBqnA;
extern TNimType NTI_M4na42GvebBMnI5wV9cYMxg;
extern TNimType NTI_vr5DoT1jILTGdRlYv1OYpw;
TNimType NTI_Y0FvJAkVbcX1wgIBeWhLOg;
extern TNimType NTI_kDPg4wXyR8DDyA0MeEjIsw;
TNimType NTI_djJYT8M31CO4H4upDByZIA;
TY_wc33gX9cDmCWKwjWAU0IECw Dl_123381;
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TY_PTBY7HwZryF5ZlXLhiuE9cw Dl_123287;
TY_PGLFr4n9aRBWHFAO4t6jqJA Dl_123421;
TY_LmiM0IShxJ1VYR39as6EpeA Dl_123001;
TY_sWlGqWNnw8S4mvjxAn82Og Dl_123459;
TY_5dgUv4jBqbFWzIpnzViqjQ Dl_123471;
TY_L3aEu9cc4nB9a9cl7KrgxeZAg Dl_122602;
STRING_LITERAL(T_jd6ZfJ12PtMN0qL7SizLLQ_4, "libSDL.so", 9);
STRING_LITERAL(T_jd6ZfJ12PtMN0qL7SizLLQ_6, "libSDL.so.1", 11);
STRING_LITERAL(T_jd6ZfJ12PtMN0qL7SizLLQ_8, "libSDL.so.0", 11);
STRING_LITERAL(T_jd6ZfJ12PtMN0qL7SizLLQ_9, "libSDL.so(|.1|.0)", 17);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_NIMCALL(NIM_BOOL, mustlock_gXoiG07I6qjPVCa6KytbHQ)(Surface_bFoWQ9a1fqAJG6BOtYsYY2g* surface0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("mustLock", "sdl.nim")
	result0 = (NIM_BOOL)0;
	nimln(2294, "sdl.nim");
	LOC1 = (NIM_BOOL)0;
	nimln(347, "system.nim");
	nimln(2294, "sdl.nim");
	LOC1 = !(((*surface0).offset == ((NI32) 0)));
	if (LOC1) goto LA2;
	nimln(347, "system.nim");
	nimln(2295, "sdl.nim");
	LOC1 = !(((NI32)((*surface0).flags & ((NI32) 16389)) == ((NI32) 0)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

N_NIMCALL(NI, savebmp_Vb25k9cSsxa7biy3zbyWA9aw)(Surface_bFoWQ9a1fqAJG6BOtYsYY2g* surface0, NCSTRING filename0) {
	NI result0;
	Rwops_X9aV6NIIXl81VrKmMNXaaIA* LOC1;
	nimfr("saveBMP", "sdl.nim")
	result0 = (NI)0;
	nimln(2283, "sdl.nim");
	LOC1 = (Rwops_X9aV6NIIXl81VrKmMNXaaIA*)0;
	LOC1 = Dl_123001(filename0, "wb");
	result0 = Dl_123421(surface0, LOC1, ((NI) 1));
	popFrame();
	return result0;
}

N_NIMCALL(NI, blitsurface_k76RTXiwMGN1XHKx6269buA)(Surface_bFoWQ9a1fqAJG6BOtYsYY2g* src0, Rect_Y0FvJAkVbcX1wgIBeWhLOg* srcrect0, Surface_bFoWQ9a1fqAJG6BOtYsYY2g* dst0, Rect_Y0FvJAkVbcX1wgIBeWhLOg* dstrect0) {
	NI result0;
	nimfr("blitSurface", "sdl.nim")
	result0 = (NI)0;
	nimln(2286, "sdl.nim");
	result0 = Dl_123459(src0, srcrect0, dst0, dstrect0);
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, sdl1_sdlInit000)(void) {
	nimfr("sdl", "sdl.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, sdl1_sdlDatInit000)(void) {
static TNimNode* T_jd6ZfJ12PtMN0qL7SizLLQ_16[14];
static TNimNode* T_jd6ZfJ12PtMN0qL7SizLLQ_17[17];
static TNimNode* T_jd6ZfJ12PtMN0qL7SizLLQ_18[2];
static TNimNode* T_jd6ZfJ12PtMN0qL7SizLLQ_19[4];
static TNimNode* T_jd6ZfJ12PtMN0qL7SizLLQ_20[4];
static TNimNode T_jd6ZfJ12PtMN0qL7SizLLQ_0[46];
NTI_bFoWQ9a1fqAJG6BOtYsYY2g.size = sizeof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g);
NTI_bFoWQ9a1fqAJG6BOtYsYY2g.kind = 18;
NTI_bFoWQ9a1fqAJG6BOtYsYY2g.base = 0;
NTI_bFoWQ9a1fqAJG6BOtYsYY2g.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_16[0] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[1];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[1].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[1].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, flags);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[1].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[1].name = "flags";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[1] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[2];
NTI_YOl3D8kldv22sO4atKEvDA.size = sizeof(Pixelformat_YOl3D8kldv22sO4atKEvDA);
NTI_YOl3D8kldv22sO4atKEvDA.kind = 18;
NTI_YOl3D8kldv22sO4atKEvDA.base = 0;
NTI_YOl3D8kldv22sO4atKEvDA.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_17[0] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[4];
NTI_r4iaLWv4Ancf4wpNWuLTXg.size = sizeof(Palette_r4iaLWv4Ancf4wpNWuLTXg);
NTI_r4iaLWv4Ancf4wpNWuLTXg.kind = 18;
NTI_r4iaLWv4Ancf4wpNWuLTXg.base = 0;
NTI_r4iaLWv4Ancf4wpNWuLTXg.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_18[0] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[6];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[6].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[6].offset = offsetof(Palette_r4iaLWv4Ancf4wpNWuLTXg, ncolors);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[6].name = "ncolors";
T_jd6ZfJ12PtMN0qL7SizLLQ_18[1] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[7];
NTI_9apUnnwImZA9bub3LK9aEySmA.size = sizeof(Color_9apUnnwImZA9bub3LK9aEySmA);
NTI_9apUnnwImZA9bub3LK9aEySmA.kind = 18;
NTI_9apUnnwImZA9bub3LK9aEySmA.base = 0;
NTI_9apUnnwImZA9bub3LK9aEySmA.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_19[0] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[9];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[9].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[9].offset = offsetof(Color_9apUnnwImZA9bub3LK9aEySmA, r);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[9].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[9].name = "r";
T_jd6ZfJ12PtMN0qL7SizLLQ_19[1] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[10];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[10].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[10].offset = offsetof(Color_9apUnnwImZA9bub3LK9aEySmA, g);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[10].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[10].name = "g";
T_jd6ZfJ12PtMN0qL7SizLLQ_19[2] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[11];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[11].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[11].offset = offsetof(Color_9apUnnwImZA9bub3LK9aEySmA, b);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[11].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[11].name = "b";
T_jd6ZfJ12PtMN0qL7SizLLQ_19[3] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[12];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[12].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[12].offset = offsetof(Color_9apUnnwImZA9bub3LK9aEySmA, unused);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[12].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[12].name = "unused";
T_jd6ZfJ12PtMN0qL7SizLLQ_0[8].len = 4; T_jd6ZfJ12PtMN0qL7SizLLQ_0[8].kind = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[8].sons = &T_jd6ZfJ12PtMN0qL7SizLLQ_19[0];
NTI_9apUnnwImZA9bub3LK9aEySmA.node = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[8];
NTI_5KyVnex9bkoLNM2672VMzKg.size = sizeof(TY_5KyVnex9bkoLNM2672VMzKg);
NTI_5KyVnex9bkoLNM2672VMzKg.kind = 16;
NTI_5KyVnex9bkoLNM2672VMzKg.base = (&NTI_9apUnnwImZA9bub3LK9aEySmA);
NTI_5KyVnex9bkoLNM2672VMzKg.flags = 3;
NTI_XBOgL4UKEgU7QdulJrhJkQ.size = sizeof(Color_9apUnnwImZA9bub3LK9aEySmA*);
NTI_XBOgL4UKEgU7QdulJrhJkQ.kind = 21;
NTI_XBOgL4UKEgU7QdulJrhJkQ.base = (&NTI_5KyVnex9bkoLNM2672VMzKg);
NTI_XBOgL4UKEgU7QdulJrhJkQ.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[7].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[7].offset = offsetof(Palette_r4iaLWv4Ancf4wpNWuLTXg, colors);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[7].typ = (&NTI_XBOgL4UKEgU7QdulJrhJkQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[7].name = "colors";
T_jd6ZfJ12PtMN0qL7SizLLQ_0[5].len = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[5].kind = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[5].sons = &T_jd6ZfJ12PtMN0qL7SizLLQ_18[0];
NTI_r4iaLWv4Ancf4wpNWuLTXg.node = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[5];
NTI_eosgyp0pX9aYfPHui6dCIHw.size = sizeof(Palette_r4iaLWv4Ancf4wpNWuLTXg*);
NTI_eosgyp0pX9aYfPHui6dCIHw.kind = 21;
NTI_eosgyp0pX9aYfPHui6dCIHw.base = (&NTI_r4iaLWv4Ancf4wpNWuLTXg);
NTI_eosgyp0pX9aYfPHui6dCIHw.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[4].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[4].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, palette);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[4].typ = (&NTI_eosgyp0pX9aYfPHui6dCIHw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[4].name = "palette";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[1] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[13];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[13].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[13].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, bitsperpixel);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[13].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[13].name = "bitsPerPixel";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[2] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[14];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[14].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[14].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, bytesperpixel);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[14].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[14].name = "bytesPerPixel";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[3] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[15];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[15].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[15].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, rloss);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[15].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[15].name = "rloss";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[4] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[16];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[16].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[16].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, gloss);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[16].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[16].name = "gloss";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[5] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[17];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[17].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[17].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, bloss);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[17].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[17].name = "bloss";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[6] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[18];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[18].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[18].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, aloss);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[18].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[18].name = "aloss";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[7] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[19];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[19].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[19].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, rshift);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[19].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[19].name = "rshift";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[8] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[20];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[20].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[20].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, gshift);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[20].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[20].name = "gshift";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[9] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[21];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[21].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[21].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, bshift);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[21].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[21].name = "bshift";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[10] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[22];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[22].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[22].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, ashift);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[22].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[22].name = "ashift";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[11] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[23];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[23].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[23].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, rmask);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[23].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[23].name = "rMask";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[12] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[24];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[24].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[24].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, gmask);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[24].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[24].name = "gMask";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[13] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[25];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[25].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[25].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, bmask);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[25].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[25].name = "bMask";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[14] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[26];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[26].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[26].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, amask);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[26].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[26].name = "aMask";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[15] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[27];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[27].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[27].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, colorkey);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[27].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[27].name = "colorkey";
T_jd6ZfJ12PtMN0qL7SizLLQ_17[16] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[28];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[28].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[28].offset = offsetof(Pixelformat_YOl3D8kldv22sO4atKEvDA, alpha);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[28].typ = (&NTI_k3HXouOuhqAKq0dx450lXQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[28].name = "alpha";
T_jd6ZfJ12PtMN0qL7SizLLQ_0[3].len = 17; T_jd6ZfJ12PtMN0qL7SizLLQ_0[3].kind = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[3].sons = &T_jd6ZfJ12PtMN0qL7SizLLQ_17[0];
NTI_YOl3D8kldv22sO4atKEvDA.node = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[3];
NTI_APtBDKdndih08ga9baTCQnQ.size = sizeof(Pixelformat_YOl3D8kldv22sO4atKEvDA*);
NTI_APtBDKdndih08ga9baTCQnQ.kind = 21;
NTI_APtBDKdndih08ga9baTCQnQ.base = (&NTI_YOl3D8kldv22sO4atKEvDA);
NTI_APtBDKdndih08ga9baTCQnQ.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[2].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[2].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, format);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[2].typ = (&NTI_APtBDKdndih08ga9baTCQnQ);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[2].name = "format";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[2] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[29];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[29].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[29].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, w);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[29].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[29].name = "w";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[3] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[30];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[30].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[30].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, h);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[30].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[30].name = "h";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[4] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[31];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[31].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[31].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, pitch);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[31].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[31].name = "pitch";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[5] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[32];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[32].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[32].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, pixels);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[32].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[32].name = "pixels";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[6] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[33];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[33].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[33].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, offset);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[33].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[33].name = "offset";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[7] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[34];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[34].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[34].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, hwdata);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[34].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[34].name = "hwdata";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[8] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[35];
NTI_Y0FvJAkVbcX1wgIBeWhLOg.size = sizeof(Rect_Y0FvJAkVbcX1wgIBeWhLOg);
NTI_Y0FvJAkVbcX1wgIBeWhLOg.kind = 18;
NTI_Y0FvJAkVbcX1wgIBeWhLOg.base = 0;
NTI_Y0FvJAkVbcX1wgIBeWhLOg.flags = 3;
T_jd6ZfJ12PtMN0qL7SizLLQ_20[0] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[37];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[37].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[37].offset = offsetof(Rect_Y0FvJAkVbcX1wgIBeWhLOg, x);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[37].typ = (&NTI_kDPg4wXyR8DDyA0MeEjIsw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[37].name = "x";
T_jd6ZfJ12PtMN0qL7SizLLQ_20[1] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[38];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[38].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[38].offset = offsetof(Rect_Y0FvJAkVbcX1wgIBeWhLOg, y);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[38].typ = (&NTI_kDPg4wXyR8DDyA0MeEjIsw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[38].name = "y";
T_jd6ZfJ12PtMN0qL7SizLLQ_20[2] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[39];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[39].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[39].offset = offsetof(Rect_Y0FvJAkVbcX1wgIBeWhLOg, w);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[39].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[39].name = "w";
T_jd6ZfJ12PtMN0qL7SizLLQ_20[3] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[40];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[40].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[40].offset = offsetof(Rect_Y0FvJAkVbcX1wgIBeWhLOg, h);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[40].typ = (&NTI_M4na42GvebBMnI5wV9cYMxg);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[40].name = "h";
T_jd6ZfJ12PtMN0qL7SizLLQ_0[36].len = 4; T_jd6ZfJ12PtMN0qL7SizLLQ_0[36].kind = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[36].sons = &T_jd6ZfJ12PtMN0qL7SizLLQ_20[0];
NTI_Y0FvJAkVbcX1wgIBeWhLOg.node = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[36];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[35].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[35].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, cliprect);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[35].typ = (&NTI_Y0FvJAkVbcX1wgIBeWhLOg);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[35].name = "clipRect";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[9] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[41];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[41].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[41].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, unused1);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[41].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[41].name = "unused1";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[10] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[42];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[42].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[42].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, locked);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[42].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[42].name = "locked";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[11] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[43];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[43].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[43].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, blitmap);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[43].typ = (&NTI_vr5DoT1jILTGdRlYv1OYpw);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[43].name = "blitmap";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[12] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[44];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[44].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[44].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, formatversion);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[44].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[44].name = "formatVersion";
T_jd6ZfJ12PtMN0qL7SizLLQ_16[13] = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[45];
T_jd6ZfJ12PtMN0qL7SizLLQ_0[45].kind = 1;
T_jd6ZfJ12PtMN0qL7SizLLQ_0[45].offset = offsetof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g, refcount);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[45].typ = (&NTI_nlCscttRCss70IBTyuBqnA);
T_jd6ZfJ12PtMN0qL7SizLLQ_0[45].name = "refcount";
T_jd6ZfJ12PtMN0qL7SizLLQ_0[0].len = 14; T_jd6ZfJ12PtMN0qL7SizLLQ_0[0].kind = 2; T_jd6ZfJ12PtMN0qL7SizLLQ_0[0].sons = &T_jd6ZfJ12PtMN0qL7SizLLQ_16[0];
NTI_bFoWQ9a1fqAJG6BOtYsYY2g.node = &T_jd6ZfJ12PtMN0qL7SizLLQ_0[0];
NTI_djJYT8M31CO4H4upDByZIA.size = sizeof(Surface_bFoWQ9a1fqAJG6BOtYsYY2g*);
NTI_djJYT8M31CO4H4upDByZIA.kind = 21;
NTI_djJYT8M31CO4H4upDByZIA.base = (&NTI_bFoWQ9a1fqAJG6BOtYsYY2g);
NTI_djJYT8M31CO4H4upDByZIA.flags = 3;
if (!((T_jd6ZfJ12PtMN0qL7SizLLQ_2 = nimLoadLibrary((NimStringDesc*) &T_jd6ZfJ12PtMN0qL7SizLLQ_4))
||(T_jd6ZfJ12PtMN0qL7SizLLQ_2 = nimLoadLibrary((NimStringDesc*) &T_jd6ZfJ12PtMN0qL7SizLLQ_6))
||(T_jd6ZfJ12PtMN0qL7SizLLQ_2 = nimLoadLibrary((NimStringDesc*) &T_jd6ZfJ12PtMN0qL7SizLLQ_8))
)) nimLoadLibraryError((NimStringDesc*) &T_jd6ZfJ12PtMN0qL7SizLLQ_9);
	Dl_123342 = (TY_CXl344VSAMaA2Bw9bCvgXcA) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_MapRGBA");
	Dl_122804 = (TY_09bvyvHFtWbkzL5AHgf0bKw) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_GetError");
	Dl_123402 = (TY_2eKqBOvpeTZKPUWu5YiExA) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_FreeSurface");
	Dl_123381 = (TY_wc33gX9cDmCWKwjWAU0IECw) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_CreateRGBSurface");
	Dl_123287 = (TY_PTBY7HwZryF5ZlXLhiuE9cw) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_SetVideoMode");
	Dl_123421 = (TY_PGLFr4n9aRBWHFAO4t6jqJA) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_SaveBMP_RW");
	Dl_123001 = (TY_LmiM0IShxJ1VYR39as6EpeA) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_RWFromFile");
	Dl_123459 = (TY_sWlGqWNnw8S4mvjxAn82Og) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_UpperBlit");
	Dl_123471 = (TY_5dgUv4jBqbFWzIpnzViqjQ) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_FillRect");
	Dl_122602 = (TY_L3aEu9cc4nB9a9cl7KrgxeZAg) nimGetProcAddr(T_jd6ZfJ12PtMN0qL7SizLLQ_2, "SDL_Init");
}

