/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cgp/Develop/hexe/nimcache/stdlib_strutils.o /home/cgp/Develop/hexe/nimcache/stdlib_strutils.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Slice_WC2BEYwxNBO9aTbMc8sJqPg Slice_WC2BEYwxNBO9aTbMc8sJqPg;
typedef struct Valueerror_Gi06FkNeykJn7mrqRZYrkA Valueerror_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Slice_WC2BEYwxNBO9aTbMc8sJqPg  {
NI a;
NI b;
};
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
N_NIMCALL(void, reverse_LoixoqZetR6FfezoPedx8w)(NimStringDesc** a0, NI a0Len0);
N_NIMCALL(void, reverse_XQiN4wExsmIg8NFBmG3ObA)(NimStringDesc** a0, NI a0Len0, NI first0, NI last0);
static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, contains_tKnjuJQDI4zGjoGUKWyD2wstrutils)(Slice_WC2BEYwxNBO9aTbMc8sJqPg s0, NI value0);
N_NIMCALL(NF, round_FL9bhksfuQsfLDCxRHuknsg)(NF x0, NI places0);
static N_INLINE(void, HEX2AHEX3D_7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x0, NF y0);
static N_INLINE(void, HEX2BHEX3D_7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x0, NF y0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(NimStringDesc*, mnewString)(NI len0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x0);
static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0);
N_NIMCALL(NI, npuParseInt)(NimStringDesc* s0, NI* number0, NI start0);
static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0);
N_NOINLINE(void, raiseRangeError)(NI64 val0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0);
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(T_JGc9b9bh2D3nTdUR7TGyq8aA_4, "0123456789ABCDEF", 16);
STRING_LITERAL(T_JGc9b9bh2D3nTdUR7TGyq8aA_5, "invalid integer: ", 17);

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, find_b3HPX1XboPhUmnxkTjazFQstrutils)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NI result0;
	nimfr("find", "system.nim")
{	result0 = (NI)0;
	{
		NIM_CHAR i_PK51OczLhe60IMTnpDtj2Q;
		NI i_PK51OczLhe60IMTnpDtj2Q_2;
		i_PK51OczLhe60IMTnpDtj2Q = (NIM_CHAR)0;
		nimln(1999, "system.nim");
		i_PK51OczLhe60IMTnpDtj2Q_2 = ((NI) 0);
		{
			nimln(2000, "system.nim");
			while (1) {
				NI T_JGc9b9bh2D3nTdUR7TGyq8aA_2;
				NI T_JGc9b9bh2D3nTdUR7TGyq8aA_3;
				nimln(1999, "system.nim");
				nimln(2232, "system.nim");
				if (!(i_PK51OczLhe60IMTnpDtj2Q_2 < a0Len0)) goto LA3;
				nimln(2001, "system.nim");
				if ((NU)(i_PK51OczLhe60IMTnpDtj2Q_2) >= (NU)(a0Len0)) raiseIndexError();
				i_PK51OczLhe60IMTnpDtj2Q = a0[i_PK51OczLhe60IMTnpDtj2Q_2];
				nimln(2233, "system.nim");
				{
					if (!((NU8)(i_PK51OczLhe60IMTnpDtj2Q) == (NU8)(item0))) goto LA6;
					goto BeforeRet;
				}
				LA6: ;
				nimln(2234, "system.nim");
				T_JGc9b9bh2D3nTdUR7TGyq8aA_2 = addInt(result0, ((NI) 1));
				result0 = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_2);
				nimln(1999, "system.nim");
				T_JGc9b9bh2D3nTdUR7TGyq8aA_3 = addInt(i_PK51OczLhe60IMTnpDtj2Q_2, ((NI) 1));
				i_PK51OczLhe60IMTnpDtj2Q_2 = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_3);
			} LA3: ;
		}
	}
	nimln(2235, "system.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_I9cy9aN2znlBRynMcXN4pBGgstrutils)(NIM_CHAR* a0, NI a0Len0, NIM_CHAR item0) {
	NIM_BOOL result0;
	NI LOC1;
	nimfr("contains", "system.nim")
{	result0 = (NIM_BOOL)0;
	nimln(2240, "system.nim");
	LOC1 = (NI)0;
	LOC1 = find_b3HPX1XboPhUmnxkTjazFQstrutils(a0, a0Len0, item0);
	result0 = (((NI) 0) <= LOC1);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(NIM_BOOL, contains_tKnjuJQDI4zGjoGUKWyD2wstrutils)(Slice_WC2BEYwxNBO9aTbMc8sJqPg s0, NI value0) {
	NIM_BOOL result0;
	NIM_BOOL LOC1;
	nimfr("contains", "system.nim")
	result0 = (NIM_BOOL)0;
	nimln(1122, "system.nim");
	LOC1 = (NIM_BOOL)0;
	LOC1 = (((NI) (s0.a)) <= ((NI) (value0)));
	if (!(LOC1)) goto LA2;
	LOC1 = (((NI) (value0)) <= ((NI) (s0.b)));
	LA2: ;
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(void, HEX2AHEX3D_7kHiltrvRlcg6wSYR3CxAwstrutils)(NF* x0, NF y0) {
	nimfr("*=", "system.nim")
	nimln(3402, "system.nim");
	(*x0) = ((NF)((*x0)) * (NF)(y0));
	popFrame();
}

static N_INLINE(void, HEX2BHEX3D_7kHiltrvRlcg6wSYR3CxAw_2strutils)(NF* x0, NF y0) {
	nimfr("+=", "system.nim")
	nimln(3392, "system.nim");
	(*x0) = ((NF)((*x0)) + (NF)(y0));
	popFrame();
}

N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x0, NI len0) {
	NimStringDesc* result0;
	NI64 n0;
	nimfr("toHex", "strutils.nim")
	result0 = (NimStringDesc*)0;
	n0 = x0;
	result0 = mnewString(((NI) (len0)));
	{
		NI j_jtVhfoYpXeRJUwm8SjFcYA;
		NI HEX3Atmp_DL9bYykBTQPZcxEnrzhm9cYg;
		NI res_K9cSgDvHGGBxWzGn3Ng0Dkw;
		j_jtVhfoYpXeRJUwm8SjFcYA = (NI)0;
		HEX3Atmp_DL9bYykBTQPZcxEnrzhm9cYg = (NI)0;
		HEX3Atmp_DL9bYykBTQPZcxEnrzhm9cYg = (NI)(((NI) (len0)) - ((NI) 1));
		res_K9cSgDvHGGBxWzGn3Ng0Dkw = ((NI) (HEX3Atmp_DL9bYykBTQPZcxEnrzhm9cYg));
		{
			while (1) {
				if (!(((NI) 0) <= res_K9cSgDvHGGBxWzGn3Ng0Dkw)) goto LA3;
				j_jtVhfoYpXeRJUwm8SjFcYA = ((NI) (res_K9cSgDvHGGBxWzGn3Ng0Dkw));
				result0->data[j_jtVhfoYpXeRJUwm8SjFcYA] = ((NimStringDesc*) &T_JGc9b9bh2D3nTdUR7TGyq8aA_4)->data[(NI64)(n0 & IL64(15))];
				n0 = (NI64)((NU64)(n0) >> (NU64)(((NI) 4)));
				{
					NIM_BOOL LOC6;
					LOC6 = (NIM_BOOL)0;
					LOC6 = (n0 == IL64(0));
					if (!(LOC6)) goto LA7;
					LOC6 = (x0 < IL64(0));
					LA7: ;
					if (!LOC6) goto LA8;
					n0 = IL64(-1);
				}
				LA8: ;
				res_K9cSgDvHGGBxWzGn3Ng0Dkw -= ((NI) 1);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s0) {
	NI result0;
	NI i0;
	nimfr("parseHexInt", "strutils.nim")
	result0 = (NI)0;
	i0 = ((NI) 0);
	{
		NIM_BOOL LOC3;
		NIM_BOOL LOC5;
		LOC3 = (NIM_BOOL)0;
		LOC3 = ((NU8)(s0->data[i0]) == (NU8)(48));
		if (!(LOC3)) goto LA4;
		LOC5 = (NIM_BOOL)0;
		LOC5 = ((NU8)(s0->data[(NI)(i0 + ((NI) 1))]) == (NU8)(120));
		if (LOC5) goto LA6;
		LOC5 = ((NU8)(s0->data[(NI)(i0 + ((NI) 1))]) == (NU8)(88));
		LA6: ;
		LOC3 = LOC5;
		LA4: ;
		if (!LOC3) goto LA7;
		i0 += ((NI) 2);
	}
	goto LA1;
	LA7: ;
	{
		if (!((NU8)(s0->data[i0]) == (NU8)(35))) goto LA10;
		i0 += ((NI) 1);
	}
	goto LA1;
	LA10: ;
	LA1: ;
	{
		while (1) {
			switch (((NU8)(s0->data[i0]))) {
			case 95:
			{
				i0 += ((NI) 1);
			}
			break;
			case 48 ... 57:
			{
				result0 = (NI)((NI)((NU64)(result0) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) (((NU8)(s0->data[i0])))) - ((NI) 48)))));
				i0 += ((NI) 1);
			}
			break;
			case 97 ... 102:
			{
				result0 = (NI)((NI)((NU64)(result0) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) ((NI)(((NI) (((NU8)(s0->data[i0])))) - ((NI) 97)))) + ((NI) 10)))));
				i0 += ((NI) 1);
			}
			break;
			case 65 ... 70:
			{
				result0 = (NI)((NI)((NU64)(result0) << (NU64)(((NI) 4))) | ((NI) ((NI)(((NI) ((NI)(((NI) (((NU8)(s0->data[i0])))) - ((NI) 65)))) + ((NI) 10)))));
				i0 += ((NI) 1);
			}
			break;
			case 0:
			{
				goto LA12;
			}
			break;
			default:
			{
				Valueerror_Gi06FkNeykJn7mrqRZYrkA* e_s9a8HynXzFiyMdNic0A3chQ;
				NimStringDesc* LOC20;
				e_s9a8HynXzFiyMdNic0A3chQ = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*)0;
				e_s9a8HynXzFiyMdNic0A3chQ = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg), sizeof(Valueerror_Gi06FkNeykJn7mrqRZYrkA));
				(*e_s9a8HynXzFiyMdNic0A3chQ).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA);
				LOC20 = (NimStringDesc*)0;
				LOC20 = rawNewString(s0->Sup.len + 17);
appendString(LOC20, ((NimStringDesc*) &T_JGc9b9bh2D3nTdUR7TGyq8aA_5));
appendString(LOC20, s0);
				asgnRefNoCycle((void**) (&(*e_s9a8HynXzFiyMdNic0A3chQ).Sup.message), LOC20);
				raiseException((Exception*)e_s9a8HynXzFiyMdNic0A3chQ, "ValueError");
			}
			break;
			}
		}
	} LA12: ;
	popFrame();
	return result0;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0) {
	(*dest0).data[((*dest0).Sup.len)- 0] = c0;
	(*dest0).data[((NI)((*dest0).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest0).Sup.len += ((NI) 1);
}

N_NIMCALL(NimStringDesc*, nsuIntToStr)(NI x0, NI minchars0) {
	NimStringDesc* result0;
	nimfr("intToStr", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = nimIntToStr((x0 > 0? (x0) : -(x0)));
	{
		NI i_0WI5azliNHYkVYV8ChzA6A;
		NI HEX3Atmp_fSOxXjlVMUMPmJjXyPHj4Q;
		NI res_9aPdOY13II9avtAIzc2NHzgg;
		i_0WI5azliNHYkVYV8ChzA6A = (NI)0;
		HEX3Atmp_fSOxXjlVMUMPmJjXyPHj4Q = (NI)0;
		HEX3Atmp_fSOxXjlVMUMPmJjXyPHj4Q = (NI)(((NI) (minchars0)) - (result0 ? result0->Sup.len : 0));
		res_9aPdOY13II9avtAIzc2NHzgg = ((NI) 1);
		{
			while (1) {
				NimStringDesc* LOC4;
				if (!(res_9aPdOY13II9avtAIzc2NHzgg <= HEX3Atmp_fSOxXjlVMUMPmJjXyPHj4Q)) goto LA3;
				i_0WI5azliNHYkVYV8ChzA6A = res_9aPdOY13II9avtAIzc2NHzgg;
				LOC4 = (NimStringDesc*)0;
				LOC4 = rawNewString(result0->Sup.len + 1);
appendChar(LOC4, 48);
appendString(LOC4, result0);
				result0 = LOC4;
				res_9aPdOY13II9avtAIzc2NHzgg += ((NI) 1);
			} LA3: ;
		}
	}
	{
		NimStringDesc* LOC9;
		if (!(x0 < ((NI) 0))) goto LA7;
		LOC9 = (NimStringDesc*)0;
		LOC9 = rawNewString(result0->Sup.len + 1);
appendChar(LOC9, 45);
appendString(LOC9, result0);
		result0 = LOC9;
	}
	LA7: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuRepeatChar)(NIM_CHAR c0, NI count0) {
	NimStringDesc* result0;
	nimfr("repeat", "strutils.nim")
	result0 = (NimStringDesc*)0;
	result0 = mnewString(count0);
	{
		NI i_3GQd65NoQ8GRAK9aKcUCkqQ;
		NI HEX3Atmp_dzdTGA9bp9cdFQ4FdPqfyPrQ;
		NI res_ZCK9av0K5RQEcyuf9cJ7G5eg;
		i_3GQd65NoQ8GRAK9aKcUCkqQ = (NI)0;
		HEX3Atmp_dzdTGA9bp9cdFQ4FdPqfyPrQ = (NI)0;
		HEX3Atmp_dzdTGA9bp9cdFQ4FdPqfyPrQ = (NI)(((NI) (count0)) - ((NI) 1));
		res_ZCK9av0K5RQEcyuf9cJ7G5eg = ((NI) 0);
		{
			while (1) {
				if (!(res_ZCK9av0K5RQEcyuf9cJ7G5eg <= ((NI) (HEX3Atmp_dzdTGA9bp9cdFQ4FdPqfyPrQ)))) goto LA3;
				i_3GQd65NoQ8GRAK9aKcUCkqQ = ((NI) (res_ZCK9av0K5RQEcyuf9cJ7G5eg));
				result0->data[i_3GQd65NoQ8GRAK9aKcUCkqQ] = c0;
				res_ZCK9av0K5RQEcyuf9cJ7G5eg += ((NI) 1);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NI, nsuParseInt)(NimStringDesc* s0) {
	NI result0;
	NI L0;
	nimfr("parseInt", "strutils.nim")
	result0 = (NI)0;
	L0 = npuParseInt(s0, (&result0), ((NI) 0));
	{
		NIM_BOOL LOC3;
		Valueerror_Gi06FkNeykJn7mrqRZYrkA* e_h9cJEojVqoNVqDKVeb0IKjg;
		NimStringDesc* LOC7;
		LOC3 = (NIM_BOOL)0;
		LOC3 = !((L0 == (s0 ? s0->Sup.len : 0)));
		if (LOC3) goto LA4;
		LOC3 = (L0 == ((NI) 0));
		LA4: ;
		if (!LOC3) goto LA5;
		e_h9cJEojVqoNVqDKVeb0IKjg = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*)0;
		e_h9cJEojVqoNVqDKVeb0IKjg = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg), sizeof(Valueerror_Gi06FkNeykJn7mrqRZYrkA));
		(*e_h9cJEojVqoNVqDKVeb0IKjg).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA);
		LOC7 = (NimStringDesc*)0;
		LOC7 = rawNewString(s0->Sup.len + 17);
appendString(LOC7, ((NimStringDesc*) &T_JGc9b9bh2D3nTdUR7TGyq8aA_5));
appendString(LOC7, s0);
		asgnRefNoCycle((void**) (&(*e_h9cJEojVqoNVqDKVeb0IKjg).Sup.message), LOC7);
		raiseException((Exception*)e_h9cJEojVqoNVqDKVeb0IKjg, "ValueError");
	}
	LA5: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, chckRange)(NI i0, NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (a0 <= i0);
		if (!(LOC3)) goto LA4;
		LOC3 = (i0 <= b0);
		LA4: ;
		if (!LOC3) goto LA5;
		result0 = i0;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i0)));
	}
	LA1: ;
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NIM_CHAR, nsuToLowerAsciiChar)(NIM_CHAR c0) {
	NIM_CHAR result0;
	nimfr("toLowerAscii", "strutils.nim")
	result0 = (NIM_CHAR)0;
	nimln(209, "strutils.nim");
	{
		NI T_JGc9b9bh2D3nTdUR7TGyq8aA_7;
		if (!(((NU8)(c0)) >= ((NU8)(65)) && ((NU8)(c0)) <= ((NU8)(90)))) goto LA3;
		nimln(210, "strutils.nim");
		T_JGc9b9bh2D3nTdUR7TGyq8aA_7 = addInt(((NI) (((NU8)(c0)))), ((NI) 32));
		result0 = ((NIM_CHAR) (((NI)chckRange((NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_7), ((NI) 0), ((NI) 255)))));
	}
	goto LA1;
	LA3: ;
	{
		nimln(212, "strutils.nim");
		result0 = c0;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NimStringDesc*, nsuToLowerAsciiStr)(NimStringDesc* s0) {
	NimStringDesc* result0;
	nimfr("toLowerAscii", "strutils.nim")
	result0 = (NimStringDesc*)0;
	nimln(221, "strutils.nim");
	result0 = mnewString(((NI)chckRange((s0 ? s0->Sup.len : 0), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	{
		NI i_Q4ErNf9cOnD9bQiwEaTZI6PA;
		NI HEX3Atmp_GYbw9c9aYs4vIjnQGiCqmtRg;
		NI T_JGc9b9bh2D3nTdUR7TGyq8aA_6;
		NI res_kjxR3eSoP8WNRp9c4KDSe2w;
		i_Q4ErNf9cOnD9bQiwEaTZI6PA = (NI)0;
		HEX3Atmp_GYbw9c9aYs4vIjnQGiCqmtRg = (NI)0;
		nimln(222, "strutils.nim");
		T_JGc9b9bh2D3nTdUR7TGyq8aA_6 = subInt((s0 ? s0->Sup.len : 0), ((NI) 1));
		HEX3Atmp_GYbw9c9aYs4vIjnQGiCqmtRg = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_6);
		nimln(1908, "system.nim");
		res_kjxR3eSoP8WNRp9c4KDSe2w = ((NI) 0);
		{
			nimln(1909, "system.nim");
			while (1) {
				NI T_JGc9b9bh2D3nTdUR7TGyq8aA_8;
				nimln(1908, "system.nim");
				if (!(res_kjxR3eSoP8WNRp9c4KDSe2w <= HEX3Atmp_GYbw9c9aYs4vIjnQGiCqmtRg)) goto LA3;
				nimln(1910, "system.nim");
				i_Q4ErNf9cOnD9bQiwEaTZI6PA = res_kjxR3eSoP8WNRp9c4KDSe2w;
				nimln(223, "strutils.nim");
				if ((NU)(i_Q4ErNf9cOnD9bQiwEaTZI6PA) > (NU)(result0->Sup.len)) raiseIndexError();
				if ((NU)(i_Q4ErNf9cOnD9bQiwEaTZI6PA) > (NU)(s0->Sup.len)) raiseIndexError();
				result0->data[i_Q4ErNf9cOnD9bQiwEaTZI6PA] = nsuToLowerAsciiChar(s0->data[i_Q4ErNf9cOnD9bQiwEaTZI6PA]);
				nimln(1908, "system.nim");
				T_JGc9b9bh2D3nTdUR7TGyq8aA_8 = addInt(res_kjxR3eSoP8WNRp9c4KDSe2w, ((NI) 1));
				res_kjxR3eSoP8WNRp9c4KDSe2w = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_8);
			} LA3: ;
		}
	}
	popFrame();
	return result0;
}

N_NIMCALL(NI, nsuCmpIgnoreCase)(NimStringDesc* a0, NimStringDesc* b0) {
	NI result0;
	NI i0;
	NI m0;
	NI T_JGc9b9bh2D3nTdUR7TGyq8aA_11;
	nimfr("cmpIgnoreCase", "strutils.nim")
{	result0 = (NI)0;
	nimln(410, "strutils.nim");
	i0 = ((NI) 0);
	nimln(411, "strutils.nim");
	m0 = (((a0 ? a0->Sup.len : 0) <= (b0 ? b0->Sup.len : 0)) ? (a0 ? a0->Sup.len : 0) : (b0 ? b0->Sup.len : 0));
	{
		nimln(412, "strutils.nim");
		while (1) {
			NIM_CHAR LOC3;
			NIM_CHAR LOC4;
			NI T_JGc9b9bh2D3nTdUR7TGyq8aA_9;
			NI T_JGc9b9bh2D3nTdUR7TGyq8aA_10;
			if (!(i0 < m0)) goto LA2;
			nimln(413, "strutils.nim");
			if ((NU)(i0) > (NU)(a0->Sup.len)) raiseIndexError();
			LOC3 = (NIM_CHAR)0;
			LOC3 = nsuToLowerAsciiChar(a0->data[i0]);
			if ((NU)(i0) > (NU)(b0->Sup.len)) raiseIndexError();
			LOC4 = (NIM_CHAR)0;
			LOC4 = nsuToLowerAsciiChar(b0->data[i0]);
			T_JGc9b9bh2D3nTdUR7TGyq8aA_9 = subInt(((NI) (((NU8)(LOC3)))), ((NI) (((NU8)(LOC4)))));
			result0 = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_9);
			nimln(414, "strutils.nim");
			{
				nimln(347, "system.nim");
				nimln(414, "strutils.nim");
				if (!!((result0 == ((NI) 0)))) goto LA7;
				goto BeforeRet;
			}
			LA7: ;
			nimln(415, "strutils.nim");
			T_JGc9b9bh2D3nTdUR7TGyq8aA_10 = addInt(i0, ((NI) 1));
			i0 = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_10);
		} LA2: ;
	}
	nimln(416, "strutils.nim");
	T_JGc9b9bh2D3nTdUR7TGyq8aA_11 = subInt((a0 ? a0->Sup.len : 0), (b0 ? b0->Sup.len : 0));
	result0 = (NI)(T_JGc9b9bh2D3nTdUR7TGyq8aA_11);
	}BeforeRet: ;
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void) {
	nimfr("strutils", "strutils.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void) {
}

