/* Generated by Nim Compiler v0.16.0 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/usr/lib/nim -o /home/cgp/Develop/hexe/nimcache/stdlib_colors.o /home/cgp/Develop/hexe/nimcache/stdlib_colors.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef linux
typedef struct TY_tO8lEewTy64TOox5ey7nMQ TY_tO8lEewTy64TOox5ey7nMQ;
typedef struct TY_XOVT24GHXwqiEj5GCsEGCA TY_XOVT24GHXwqiEj5GCsEGCA;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Valueerror_Gi06FkNeykJn7mrqRZYrkA Valueerror_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell_1zcF9cV8XIAtbN8h5HRUB8g Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct Cellseq_Axo1XVm9aaQueTOldv8le5w Cellseq_Axo1XVm9aaQueTOldv8le5w;
typedef struct Gcheap_1TRH1TZMaVZTnLNcIHuNFQ Gcheap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct Gcstack_7fytPA5bBsob6See21YMRA Gcstack_7fytPA5bBsob6See21YMRA;
typedef struct Memregion_x81NhDv59b8ercDZ9bi85jyg Memregion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct Smallchunk_tXn60W2f8h3jgAYdEmy5NQ Smallchunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct Llchunk_XsENErzHIZV9bhvyJx56wGw Llchunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct Bigchunk_Rv9c70Uhp2TytkX7eH78qEg Bigchunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct Intset_EZObFrE3NC9bIb3YMkY9crZA Intset_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct Trunk_W0r8S0Y3UGke6T9bIUWnnuw Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct Avlnode_IaqjtwKhxLEpvDS9bct9blEw Avlnode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct Gcstat_0RwLoVBHZPfUAcLczmfQAg Gcstat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct Cellset_jG87P0AI9aZtss9ccTYBIISQ Cellset_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct Pagedesc_fublkgIY4LG3mT51LU2WHg Pagedesc_fublkgIY4LG3mT51LU2WHg;
typedef struct Basechunk_Sdq7WpT6qAH858F5ZEdG3w Basechunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct Freecell_u6M5LHprqzkn9axr04yg9bGQ Freecell_u6M5LHprqzkn9axr04yg9bGQ;
struct TY_tO8lEewTy64TOox5ey7nMQ {
NI Field0;
NI Field1;
NI Field2;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct TY_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
typedef TY_XOVT24GHXwqiEj5GCsEGCA TY_q6NkqhYAaVnMZpcgQ6A6Fg[140];
typedef NU8 Tnimkind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set;
typedef N_NIMCALL_PTR(void, TY_ojoeKfW4VYIm36I9cpDTQIg) (void* p0, NI op0);
typedef N_NIMCALL_PTR(void*, TY_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p0);
struct  TNimType  {
NI size;
Tnimkind_jIBKr1ejBgsfM33Kxw4j7A kind;
Tnimtypeflag_v8QUszD1sWlSIWZz7mC4bQ_Set flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY_ojoeKfW4VYIm36I9cpDTQIg marker;
TY_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror_Gi06FkNeykJn7mrqRZYrkA  {
  Exception Sup;
};
typedef NU8 Tnimnodekind_unfNsxrcATrufDZmpBq4HQ;
struct  TNimNode  {
Tnimnodekind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell_1zcF9cV8XIAtbN8h5HRUB8g  {
NI refcount;
TNimType* typ;
};
struct  Cellseq_Axo1XVm9aaQueTOldv8le5w  {
NI len;
NI cap;
Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* TY_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef Trunk_W0r8S0Y3UGke6T9bIUWnnuw* TY_lh2A89ahMmYg9bCmpVaplLbA[256];
struct  Intset_EZObFrE3NC9bIb3YMkY9crZA  {
TY_lh2A89ahMmYg9bCmpVaplLbA data;
};
struct  Memregion_x81NhDv59b8ercDZ9bi85jyg  {
NI minlargeobj;
NI maxlargeobj;
TY_SiRwrEKZdLgxqz9a9aoVBglg freesmallchunks;
Llchunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* freechunkslist;
Intset_EZObFrE3NC9bIb3YMkY9crZA chunkstarts;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* root;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* last;
Avlnode_IaqjtwKhxLEpvDS9bct9blEw* freeavlnodes;
NIM_BOOL locked;
NIM_BOOL blockchunksizeincrease;
NI nextchunksize;
};
struct  Gcstat_0RwLoVBHZPfUAcLczmfQAg  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Cellset_jG87P0AI9aZtss9ccTYBIISQ  {
NI counter;
NI max;
Pagedesc_fublkgIY4LG3mT51LU2WHg* head;
Pagedesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct  Gcheap_1TRH1TZMaVZTnLNcIHuNFQ  {
Gcstack_7fytPA5bBsob6See21YMRA* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq_Axo1XVm9aaQueTOldv8le5w zct;
Cellseq_Axo1XVm9aaQueTOldv8le5w decstack;
Cellseq_Axo1XVm9aaQueTOldv8le5w tempstack;
NI recgclock;
Memregion_x81NhDv59b8ercDZ9bi85jyg region;
Gcstat_0RwLoVBHZPfUAcLczmfQAg stat;
Cellset_jG87P0AI9aZtss9ccTYBIISQ marked;
Cellseq_Axo1XVm9aaQueTOldv8le5w additionalroots;
};
struct  Gcstack_7fytPA5bBsob6See21YMRA  {
Gcstack_7fytPA5bBsob6See21YMRA* prev;
Gcstack_7fytPA5bBsob6See21YMRA* next;
void* starts;
void* pos;
NI maxstacksize;
};
struct  Basechunk_Sdq7WpT6qAH858F5ZEdG3w  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk_tXn60W2f8h3jgAYdEmy5NQ  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* next;
Smallchunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
Freecell_u6M5LHprqzkn9axr04yg9bGQ* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk_XsENErzHIZV9bhvyJx56wGw  {
NI size;
NI acc;
Llchunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct  Bigchunk_Rv9c70Uhp2TytkX7eH78qEg  {
  Basechunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* next;
Bigchunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NI align;
NF data;
};
typedef NI TY_9a8QARi5WsUggNU9bom7kzTQ[8];
struct  Trunk_W0r8S0Y3UGke6T9bIUWnnuw  {
Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
typedef Avlnode_IaqjtwKhxLEpvDS9bct9blEw* TY_0aOLqZchNi8nWtMTi8ND8w[2];
struct  Avlnode_IaqjtwKhxLEpvDS9bct9blEw  {
TY_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperbound;
NI level;
};
struct  Pagedesc_fublkgIY4LG3mT51LU2WHg  {
Pagedesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
TY_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct  Freecell_u6M5LHprqzkn9axr04yg9bGQ  {
Freecell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zerofield;
};
static N_INLINE(NI, satplus_eBbWMf0ghXjNCk0Jl2gnOQcolors)(NI a0, NI b0);
static N_INLINE(void, nimFrame)(TFrame* s0);
N_NOINLINE(void, stackoverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, satminus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors)(NI a0, NI b0);
N_NIMCALL(NI, HEX2B_gJIJ0TjY9cb0kRs9aHpNdEoA)(NI a0, NI b0);
N_NIMCALL(NI, HEX2D_gJIJ0TjY9cb0kRs9aHpNdEoA_2)(NI a0, NI b0);
N_NIMCALL(TY_tO8lEewTy64TOox5ey7nMQ, extractrgb_O8sfxz3IaprQZipENrCGFQ)(NI a0);
N_NIMCALL(NI, intensity_V4kCo8fXOcLWbXWVP5cyEw)(NI a0, NF f0);
N_NIMCALL(NimStringDesc*, HEX24_4qHnIinwHK8uhOG9bivSS9cA)(NI c0);
static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0);
N_NIMCALL(NimStringDesc*, nsuToHex)(NI64 x0, NI len0);
static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0);
static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space0);
N_NIMCALL(NI, binarystrsearch_sfDfYBE9cjkr66pIi04EogQ)(TY_XOVT24GHXwqiEj5GCsEGCA* x0, NI x0Len0, NimStringDesc* y0);
static N_INLINE(NI, subInt)(NI a0, NI b0);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a0, NI b0);
static N_INLINE(NI, divInt)(NI a0, NI b0);
N_NOINLINE(void, raiseDivByZero)(void);
N_NIMCALL(NI, cmp_xEnKsp9cfvO7Do9cTYXo8eJw)(NimStringDesc* x0, NimStringDesc* y0);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NI, parsecolor_GKC40jw0DFGObWjkYljZnw)(NimStringDesc* name0);
N_NIMCALL(NI, nsuParseHexInt)(NimStringDesc* s0);
N_NIMCALL(void*, newObj)(TNimType* typ0, NI size0);
static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0);
static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0);
static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NOINLINE(void, addzct_fCDI7oO1NNVXXURtxSzsRw)(Cellseq_Axo1XVm9aaQueTOldv8le5w* s0, Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0);
N_NIMCALL(void, raiseException)(Exception* e0, NCSTRING ename0);
N_NIMCALL(NIM_BOOL, iscolor_pxBV1VWuv6nVnMvTQgopyg)(NimStringDesc* name0);
N_NIMCALL(NI, rgb_s6fKO9c2ZHh9bXQ1gD9as9bwtw)(NI r0, NI g0, NI b0);
extern TFrame* frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA;
extern Gcheap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_2, "aliceblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_3, "antiquewhite", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_4, "aqua", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_5, "aquamarine", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_6, "azure", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_7, "beige", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_8, "bisque", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_9, "black", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_10, "blanchedalmond", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_11, "blue", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_12, "blueviolet", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_13, "brown", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_14, "burlywood", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_15, "cadetblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_16, "chartreuse", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_17, "chocolate", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_18, "coral", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_19, "cornflowerblue", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_20, "cornsilk", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_21, "crimson", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_22, "cyan", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_23, "darkblue", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_24, "darkcyan", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_25, "darkgoldenrod", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_26, "darkgray", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_27, "darkgreen", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_28, "darkkhaki", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_29, "darkmagenta", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_30, "darkolivegreen", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_31, "darkorange", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_32, "darkorchid", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_33, "darkred", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_34, "darksalmon", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_35, "darkseagreen", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_36, "darkslateblue", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_37, "darkslategray", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_38, "darkturquoise", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_39, "darkviolet", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_40, "deeppink", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_41, "deepskyblue", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_42, "dimgray", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_43, "dodgerblue", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_44, "firebrick", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_45, "floralwhite", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_46, "forestgreen", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_47, "fuchsia", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_48, "gainsboro", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_49, "ghostwhite", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_50, "gold", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_51, "goldenrod", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_52, "gray", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_53, "green", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_54, "greenyellow", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_55, "honeydew", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_56, "hotpink", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_57, "indianred", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_58, "indigo", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_59, "ivory", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_60, "khaki", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_61, "lavender", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_62, "lavenderblush", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_63, "lawngreen", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_64, "lemonchiffon", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_65, "lightblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_66, "lightcoral", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_67, "lightcyan", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_68, "lightgoldenrodyellow", 20);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_69, "lightgrey", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_70, "lightgreen", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_71, "lightpink", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_72, "lightsalmon", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_73, "lightseagreen", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_74, "lightskyblue", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_75, "lightslategray", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_76, "lightsteelblue", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_77, "lightyellow", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_78, "lime", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_79, "limegreen", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_80, "linen", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_81, "magenta", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_82, "maroon", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_83, "mediumaquamarine", 16);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_84, "mediumblue", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_85, "mediumorchid", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_86, "mediumpurple", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_87, "mediumseagreen", 14);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_88, "mediumslateblue", 15);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_89, "mediumspringgreen", 17);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_90, "mediumturquoise", 15);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_91, "mediumvioletred", 15);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_92, "midnightblue", 12);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_93, "mintcream", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_94, "mistyrose", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_95, "moccasin", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_96, "navajowhite", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_97, "navy", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_98, "oldlace", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_99, "olive", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_100, "olivedrab", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_101, "orange", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_102, "orangered", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_103, "orchid", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_104, "palegoldenrod", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_105, "palegreen", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_106, "paleturquoise", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_107, "palevioletred", 13);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_108, "papayawhip", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_109, "peachpuff", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_110, "peru", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_111, "pink", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_112, "plum", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_113, "powderblue", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_114, "purple", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_115, "red", 3);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_116, "rosybrown", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_117, "royalblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_118, "saddlebrown", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_119, "salmon", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_120, "sandybrown", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_121, "seagreen", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_122, "seashell", 8);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_123, "sienna", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_124, "silver", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_125, "skyblue", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_126, "slateblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_127, "slategray", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_128, "snow", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_129, "springgreen", 11);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_130, "steelblue", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_131, "tan", 3);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_132, "teal", 4);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_133, "thistle", 7);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_134, "tomato", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_135, "turquoise", 9);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_136, "violet", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_137, "wheat", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_138, "white", 5);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_139, "whitesmoke", 10);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_140, "yellow", 6);
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_141, "yellowgreen", 11);
NIM_CONST TY_q6NkqhYAaVnMZpcgQ6A6Fg colornames_U7tp4PMw3jdOdV56ZMGhvA = {{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_2),
((NI) 15792383)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_3),
((NI) 16444375)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_4),
((NI) 65535)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_5),
((NI) 8388564)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_6),
((NI) 15794175)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_7),
((NI) 16119260)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_8),
((NI) 16770244)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_9),
((NI) 0)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_10),
((NI) 16772045)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_11),
((NI) 255)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_12),
((NI) 9055202)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_13),
((NI) 10824234)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_14),
((NI) 14596231)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_15),
((NI) 6266528)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_16),
((NI) 8388352)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_17),
((NI) 13789470)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_18),
((NI) 16744272)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_19),
((NI) 6591981)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_20),
((NI) 16775388)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_21),
((NI) 14423100)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_22),
((NI) 65535)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_23),
((NI) 139)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_24),
((NI) 35723)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_25),
((NI) 12092939)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_26),
((NI) 11119017)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_27),
((NI) 25600)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_28),
((NI) 12433259)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_29),
((NI) 9109643)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_30),
((NI) 5597999)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_31),
((NI) 16747520)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_32),
((NI) 10040012)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_33),
((NI) 9109504)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_34),
((NI) 15308410)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_35),
((NI) 9419919)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_36),
((NI) 4734347)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_37),
((NI) 3100495)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_38),
((NI) 52945)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_39),
((NI) 9699539)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_40),
((NI) 16716947)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_41),
((NI) 49151)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_42),
((NI) 6908265)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_43),
((NI) 2003199)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_44),
((NI) 11674146)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_45),
((NI) 16775920)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_46),
((NI) 2263842)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_47),
((NI) 16711935)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_48),
((NI) 14474460)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_49),
((NI) 16316671)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_50),
((NI) 16766720)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_51),
((NI) 14329120)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_52),
((NI) 8421504)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_53),
((NI) 32768)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_54),
((NI) 11403055)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_55),
((NI) 15794160)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_56),
((NI) 16738740)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_57),
((NI) 13458524)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_58),
((NI) 4915330)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_59),
((NI) 16777200)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_60),
((NI) 15787660)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_61),
((NI) 15132410)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_62),
((NI) 16773365)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_63),
((NI) 8190976)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_64),
((NI) 16775885)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_65),
((NI) 11393254)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_66),
((NI) 15761536)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_67),
((NI) 14745599)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_68),
((NI) 16448210)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_69),
((NI) 13882323)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_70),
((NI) 9498256)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_71),
((NI) 16758465)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_72),
((NI) 16752762)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_73),
((NI) 2142890)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_74),
((NI) 8900346)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_75),
((NI) 7833753)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_76),
((NI) 11584734)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_77),
((NI) 16777184)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_78),
((NI) 65280)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_79),
((NI) 3329330)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_80),
((NI) 16445670)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_81),
((NI) 16711935)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_82),
((NI) 8388608)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_83),
((NI) 6737322)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_84),
((NI) 205)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_85),
((NI) 12211667)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_86),
((NI) 9662680)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_87),
((NI) 3978097)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_88),
((NI) 8087790)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_89),
((NI) 64154)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_90),
((NI) 4772300)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_91),
((NI) 13047173)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_92),
((NI) 1644912)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_93),
((NI) 16121850)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_94),
((NI) 16770273)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_95),
((NI) 16770229)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_96),
((NI) 16768685)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_97),
((NI) 128)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_98),
((NI) 16643558)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_99),
((NI) 8421376)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_100),
((NI) 7048739)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_101),
((NI) 16753920)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_102),
((NI) 16729344)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_103),
((NI) 14315734)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_104),
((NI) 15657130)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_105),
((NI) 10025880)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_106),
((NI) 11529966)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_107),
((NI) 14184595)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_108),
((NI) 16773077)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_109),
((NI) 16767673)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_110),
((NI) 13468991)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_111),
((NI) 16761035)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_112),
((NI) 14524637)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_113),
((NI) 11591910)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_114),
((NI) 8388736)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_115),
((NI) 16711680)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_116),
((NI) 12357519)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_117),
((NI) 4286945)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_118),
((NI) 9127187)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_119),
((NI) 16416882)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_120),
((NI) 16032864)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_121),
((NI) 3050327)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_122),
((NI) 16774638)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_123),
((NI) 10506797)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_124),
((NI) 12632256)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_125),
((NI) 8900331)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_126),
((NI) 6970061)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_127),
((NI) 7372944)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_128),
((NI) 16775930)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_129),
((NI) 65407)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_130),
((NI) 4620980)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_131),
((NI) 13808780)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_132),
((NI) 32896)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_133),
((NI) 14204888)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_134),
((NI) 16737095)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_135),
((NI) 4251856)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_136),
((NI) 15631086)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_137),
((NI) 16113331)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_138),
((NI) 16777215)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_139),
((NI) 16119285)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_140),
((NI) 16776960)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_141),
((NI) 10145074)}
}
;
NIM_CONST TY_q6NkqhYAaVnMZpcgQ6A6Fg T_IeCO5P1bEFfytAeZMzA9bFg_147 = {{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_2),
((NI) 15792383)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_3),
((NI) 16444375)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_4),
((NI) 65535)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_5),
((NI) 8388564)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_6),
((NI) 15794175)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_7),
((NI) 16119260)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_8),
((NI) 16770244)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_9),
((NI) 0)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_10),
((NI) 16772045)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_11),
((NI) 255)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_12),
((NI) 9055202)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_13),
((NI) 10824234)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_14),
((NI) 14596231)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_15),
((NI) 6266528)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_16),
((NI) 8388352)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_17),
((NI) 13789470)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_18),
((NI) 16744272)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_19),
((NI) 6591981)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_20),
((NI) 16775388)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_21),
((NI) 14423100)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_22),
((NI) 65535)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_23),
((NI) 139)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_24),
((NI) 35723)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_25),
((NI) 12092939)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_26),
((NI) 11119017)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_27),
((NI) 25600)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_28),
((NI) 12433259)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_29),
((NI) 9109643)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_30),
((NI) 5597999)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_31),
((NI) 16747520)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_32),
((NI) 10040012)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_33),
((NI) 9109504)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_34),
((NI) 15308410)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_35),
((NI) 9419919)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_36),
((NI) 4734347)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_37),
((NI) 3100495)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_38),
((NI) 52945)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_39),
((NI) 9699539)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_40),
((NI) 16716947)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_41),
((NI) 49151)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_42),
((NI) 6908265)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_43),
((NI) 2003199)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_44),
((NI) 11674146)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_45),
((NI) 16775920)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_46),
((NI) 2263842)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_47),
((NI) 16711935)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_48),
((NI) 14474460)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_49),
((NI) 16316671)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_50),
((NI) 16766720)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_51),
((NI) 14329120)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_52),
((NI) 8421504)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_53),
((NI) 32768)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_54),
((NI) 11403055)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_55),
((NI) 15794160)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_56),
((NI) 16738740)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_57),
((NI) 13458524)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_58),
((NI) 4915330)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_59),
((NI) 16777200)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_60),
((NI) 15787660)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_61),
((NI) 15132410)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_62),
((NI) 16773365)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_63),
((NI) 8190976)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_64),
((NI) 16775885)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_65),
((NI) 11393254)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_66),
((NI) 15761536)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_67),
((NI) 14745599)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_68),
((NI) 16448210)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_69),
((NI) 13882323)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_70),
((NI) 9498256)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_71),
((NI) 16758465)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_72),
((NI) 16752762)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_73),
((NI) 2142890)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_74),
((NI) 8900346)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_75),
((NI) 7833753)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_76),
((NI) 11584734)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_77),
((NI) 16777184)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_78),
((NI) 65280)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_79),
((NI) 3329330)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_80),
((NI) 16445670)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_81),
((NI) 16711935)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_82),
((NI) 8388608)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_83),
((NI) 6737322)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_84),
((NI) 205)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_85),
((NI) 12211667)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_86),
((NI) 9662680)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_87),
((NI) 3978097)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_88),
((NI) 8087790)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_89),
((NI) 64154)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_90),
((NI) 4772300)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_91),
((NI) 13047173)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_92),
((NI) 1644912)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_93),
((NI) 16121850)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_94),
((NI) 16770273)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_95),
((NI) 16770229)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_96),
((NI) 16768685)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_97),
((NI) 128)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_98),
((NI) 16643558)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_99),
((NI) 8421376)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_100),
((NI) 7048739)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_101),
((NI) 16753920)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_102),
((NI) 16729344)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_103),
((NI) 14315734)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_104),
((NI) 15657130)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_105),
((NI) 10025880)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_106),
((NI) 11529966)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_107),
((NI) 14184595)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_108),
((NI) 16773077)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_109),
((NI) 16767673)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_110),
((NI) 13468991)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_111),
((NI) 16761035)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_112),
((NI) 14524637)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_113),
((NI) 11591910)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_114),
((NI) 8388736)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_115),
((NI) 16711680)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_116),
((NI) 12357519)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_117),
((NI) 4286945)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_118),
((NI) 9127187)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_119),
((NI) 16416882)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_120),
((NI) 16032864)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_121),
((NI) 3050327)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_122),
((NI) 16774638)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_123),
((NI) 10506797)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_124),
((NI) 12632256)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_125),
((NI) 8900331)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_126),
((NI) 6970061)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_127),
((NI) 7372944)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_128),
((NI) 16775930)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_129),
((NI) 65407)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_130),
((NI) 4620980)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_131),
((NI) 13808780)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_132),
((NI) 32896)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_133),
((NI) 14204888)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_134),
((NI) 16737095)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_135),
((NI) 4251856)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_136),
((NI) 15631086)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_137),
((NI) 16113331)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_138),
((NI) 16777215)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_139),
((NI) 16119285)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_140),
((NI) 16776960)}
,
{((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_141),
((NI) 10145074)}
}
;
STRING_LITERAL(T_IeCO5P1bEFfytAeZMzA9bFg_148, "unknown color: ", 15);

static N_INLINE(void, nimFrame)(TFrame* s0) {
	NI LOC1;
	LOC1 = (NI)0;
	{
		if (!(frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s0).calldepth = ((NI16) (LOC1));
	(*s0).prev = frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = s0;
	{
		if (!((*s0).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*frameptr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NI, satplus_eBbWMf0ghXjNCk0Jl2gnOQcolors)(NI a0, NI b0) {
	NI result0;
	nimfr("satPlus", "colors.nim")
	result0 = (NI)0;
	nimln(36, "colors.nim");
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	nimln(37, "colors.nim");
	{
		if (!(((NI) 255) < result0)) goto LA3;
		result0 = ((NI) 255);
	}
	LA3: ;
	popFrame();
	return result0;
}

static N_INLINE(NI, satminus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors)(NI a0, NI b0) {
	NI result0;
	nimfr("satMinus", "colors.nim")
	result0 = (NI)0;
	nimln(40, "colors.nim");
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	nimln(41, "colors.nim");
	{
		if (!(result0 < ((NI) 0))) goto LA3;
		result0 = ((NI) 0);
	}
	LA3: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, HEX2B_gJIJ0TjY9cb0kRs9aHpNdEoA)(NI a0, NI b0) {
	NI result0;
	NI ar0;
	NI ag0;
	NI ab0;
	NI br0;
	NI bg0;
	NI bb0;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("+", "colors.nim")
	result0 = (NI)0;
	nimln(23, "colors.nim");
	ar0 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln(24, "colors.nim");
	ag0 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln(25, "colors.nim");
	ab0 = (NI)(a0 & ((NI) 255));
	nimln(23, "colors.nim");
	br0 = (NI)((NI)((NU64)(b0) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln(24, "colors.nim");
	bg0 = (NI)((NI)((NU64)(b0) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln(25, "colors.nim");
	bb0 = (NI)(b0 & ((NI) 255));
	nimln(46, "colors.nim");
	nimln(28, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = (NI)0;
	LOC1 = satplus_eBbWMf0ghXjNCk0Jl2gnOQcolors(((NI) (ar0)), ((NI) (br0)));
	LOC2 = (NI)0;
	LOC2 = satplus_eBbWMf0ghXjNCk0Jl2gnOQcolors(((NI) (ag0)), ((NI) (bg0)));
	LOC3 = (NI)0;
	LOC3 = satplus_eBbWMf0ghXjNCk0Jl2gnOQcolors(((NI) (ab0)), ((NI) (bb0)));
	result0 = (NI)((NI)((NI)((NU64)(LOC1) << (NU64)(((NI) 16))) | (NI)((NU64)(LOC2) << (NU64)(((NI) 8)))) | LOC3);
	popFrame();
	return result0;
}

N_NIMCALL(NI, HEX2D_gJIJ0TjY9cb0kRs9aHpNdEoA_2)(NI a0, NI b0) {
	NI result0;
	NI ar0;
	NI ag0;
	NI ab0;
	NI br0;
	NI bg0;
	NI bb0;
	NI LOC1;
	NI LOC2;
	NI LOC3;
	nimfr("-", "colors.nim")
	result0 = (NI)0;
	nimln(23, "colors.nim");
	ar0 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln(24, "colors.nim");
	ag0 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln(25, "colors.nim");
	ab0 = (NI)(a0 & ((NI) 255));
	nimln(23, "colors.nim");
	br0 = (NI)((NI)((NU64)(b0) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln(24, "colors.nim");
	bg0 = (NI)((NI)((NU64)(b0) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln(25, "colors.nim");
	bb0 = (NI)(b0 & ((NI) 255));
	nimln(51, "colors.nim");
	nimln(28, "colors.nim");
	nimln(33, "colors.nim");
	LOC1 = (NI)0;
	LOC1 = satminus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(((NI) (ar0)), ((NI) (br0)));
	LOC2 = (NI)0;
	LOC2 = satminus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(((NI) (ag0)), ((NI) (bg0)));
	LOC3 = (NI)0;
	LOC3 = satminus_eBbWMf0ghXjNCk0Jl2gnOQ_2colors(((NI) (ab0)), ((NI) (bb0)));
	result0 = (NI)((NI)((NI)((NU64)(LOC1) << (NU64)(((NI) 16))) | (NI)((NU64)(LOC2) << (NU64)(((NI) 8)))) | LOC3);
	popFrame();
	return result0;
}

N_NIMCALL(TY_tO8lEewTy64TOox5ey7nMQ, extractrgb_O8sfxz3IaprQZipENrCGFQ)(NI a0) {
	TY_tO8lEewTy64TOox5ey7nMQ result0;
	nimfr("extractRGB", "colors.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(55, "colors.nim");
	result0.Field0 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 16))) & ((NI) 255));
	nimln(56, "colors.nim");
	result0.Field1 = (NI)((NI)((NU64)(a0) >> (NU64)(((NI) 8))) & ((NI) 255));
	nimln(57, "colors.nim");
	result0.Field2 = (NI)(a0 & ((NI) 255));
	popFrame();
	return result0;
}

N_NIMCALL(NI, intensity_V4kCo8fXOcLWbXWVP5cyEw)(NI a0, NF f0) {
	NI result0;
	NI r0;
	NI g0;
	NI b0;
	nimfr("intensity", "colors.nim")
	result0 = (NI)0;
	nimln(62, "colors.nim");
	r0 = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU64)(a0) >> (NU64)(((NI) 16))) & ((NI) 255))))))) * (NF)(f0)));
	nimln(63, "colors.nim");
	g0 = float64ToInt32(((NF)(((double) (((NI) ((NI)((NI)((NU64)(a0) >> (NU64)(((NI) 8))) & ((NI) 255))))))) * (NF)(f0)));
	nimln(64, "colors.nim");
	b0 = float64ToInt32(((NF)(((double) (((NI) ((NI)(a0 & ((NI) 255))))))) * (NF)(f0)));
	nimln(65, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(r0))) goto LA3;
		r0 = ((NI) 255);
	}
	LA3: ;
	nimln(66, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(g0))) goto LA7;
		g0 = ((NI) 255);
	}
	LA7: ;
	nimln(67, "colors.nim");
	{
		if (!((NU64)(((NI) 255)) < (NU64)(b0))) goto LA11;
		b0 = ((NI) 255);
	}
	LA11: ;
	nimln(68, "colors.nim");
	nimln(28, "colors.nim");
	nimln(68, "colors.nim");
	result0 = (NI)((NI)((NI)((NU64)(r0) << (NU64)(((NI) 16))) | (NI)((NU64)(g0) << (NU64)(((NI) 8)))) | b0);
	popFrame();
	return result0;
}

static N_INLINE(void, appendChar)(NimStringDesc* dest0, NIM_CHAR c0) {
	(*dest0).data[((*dest0).Sup.len)- 0] = c0;
	(*dest0).data[((NI)((*dest0).Sup.len + ((NI) 1)))- 0] = 0;
	(*dest0).Sup.len += ((NI) 1);
}

static N_INLINE(void, copymem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest0, void* source0, NI size0) {
	void* LOC1;
	LOC1 = (void*)0;
	LOC1 = memcpy(dest0, source0, ((size_t) (size0)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest0, NimStringDesc* src0) {
	copymem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest0).data[((*dest0).Sup.len)- 0]))), ((void*) ((*src0).data)), ((NI) ((NI)((*src0).Sup.len + ((NI) 1)))));
	(*dest0).Sup.len += (*src0).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_4qHnIinwHK8uhOG9bivSS9cA)(NI c0) {
	NimStringDesc* result0;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("$", "colors.nim")
	result0 = (NimStringDesc*)0;
	nimln(374, "colors.nim");
	LOC1 = (NimStringDesc*)0;
	LOC2 = (NimStringDesc*)0;
	LOC2 = nsuToHex(((NI64) (c0)), ((NI) 6));
	LOC1 = rawNewString(LOC2->Sup.len + 1);
appendChar(LOC1, 35);
appendString(LOC1, LOC2);
	result0 = LOC1;
	popFrame();
	return result0;
}

static N_INLINE(NI, subInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) - (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ (NI)((NU64) ~(b0))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, addInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	result0 = (NI)((NU64)(a0) + (NU64)(b0));
	{
		NIM_BOOL LOC3;
		LOC3 = (NIM_BOOL)0;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ a0));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result0 ^ b0));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result0;
}

static N_INLINE(NI, divInt)(NI a0, NI b0) {
	NI result0;
{	result0 = (NI)0;
	{
		if (!(b0 == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = (NIM_BOOL)0;
		LOC7 = (a0 == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b0 == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result0 = (NI)(a0 / b0);
	goto BeforeRet;
	}BeforeRet: ;
	return result0;
}

N_NIMCALL(NI, binarystrsearch_sfDfYBE9cjkr66pIi04EogQ)(TY_XOVT24GHXwqiEj5GCsEGCA* x0, NI x0Len0, NimStringDesc* y0) {
	NI result0;
	NI a0;
	NI b0;
	NI T_IeCO5P1bEFfytAeZMzA9bFg_142;
	nimfr("binaryStrSearch", "colors.nim")
{	result0 = (NI)0;
	nimln(378, "colors.nim");
	a0 = ((NI) 0);
	nimln(379, "colors.nim");
	T_IeCO5P1bEFfytAeZMzA9bFg_142 = subInt(x0Len0, ((NI) 1));
	b0 = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_142);
	{
		nimln(380, "colors.nim");
		while (1) {
			NI mid0;
			NI T_IeCO5P1bEFfytAeZMzA9bFg_143;
			NI T_IeCO5P1bEFfytAeZMzA9bFg_144;
			NI c0;
			if (!(a0 <= b0)) goto LA2;
			nimln(381, "colors.nim");
			T_IeCO5P1bEFfytAeZMzA9bFg_143 = addInt(a0, b0);
			T_IeCO5P1bEFfytAeZMzA9bFg_144 = divInt((NI)(T_IeCO5P1bEFfytAeZMzA9bFg_143), ((NI) 2));
			mid0 = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_144);
			nimln(382, "colors.nim");
			if ((NU)(mid0) >= (NU)(x0Len0)) raiseIndexError();
			c0 = cmp_xEnKsp9cfvO7Do9cTYXo8eJw(x0[mid0].Field0, y0);
			nimln(383, "colors.nim");
			{
				NI T_IeCO5P1bEFfytAeZMzA9bFg_145;
				if (!(c0 < ((NI) 0))) goto LA5;
				T_IeCO5P1bEFfytAeZMzA9bFg_145 = addInt(mid0, ((NI) 1));
				a0 = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_145);
			}
			goto LA3;
			LA5: ;
			{
				NI T_IeCO5P1bEFfytAeZMzA9bFg_146;
				nimln(384, "colors.nim");
				if (!(((NI) 0) < c0)) goto LA8;
				T_IeCO5P1bEFfytAeZMzA9bFg_146 = subInt(mid0, ((NI) 1));
				b0 = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_146);
			}
			goto LA3;
			LA8: ;
			{
				nimln(385, "colors.nim");
				result0 = mid0;
				goto BeforeRet;
			}
			LA3: ;
		} LA2: ;
	}
	nimln(386, "colors.nim");
	result0 = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result0;
}

static N_INLINE(Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr0) {
	Cell_1zcF9cV8XIAtbN8h5HRUB8g* result0;
	nimfr("usrToCell", "gc.nim")
	result0 = (Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln(134, "gc.nim");
	result0 = ((Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr0))) - (NU64)(((NI)sizeof(Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result0;
}

static N_INLINE(void, rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system)(Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(220, "gc.nim");
	addzct_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c0);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest0, void* src0) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(280, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(280, "gc.nim");
		if (!!((src0 == NIM_NIL))) goto LA3;
		nimln(281, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src0);
		nimln(282, "gc.nim");
		(*c0).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(283, "gc.nim");
	{
		Cell_1zcF9cV8XIAtbN8h5HRUB8g* c0;
		nimln(347, "system.nim");
		nimln(283, "gc.nim");
		if (!!(((*dest0) == NIM_NIL))) goto LA7;
		nimln(284, "gc.nim");
		c0 = usrtocell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest0));
		nimln(285, "gc.nim");
		{
			(*c0).refcount -= ((NI) 8);
			if (!((NU64)((*c0).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(286, "gc.nim");
			rtladdzct_MV4BBk6J1qu70IbBxwEn4w_2system(c0);
		}
		LA11: ;
	}
	LA7: ;
	nimln(287, "gc.nim");
	(*dest0) = src0;
	popFrame();
}

N_NIMCALL(NI, parsecolor_GKC40jw0DFGObWjkYljZnw)(NimStringDesc* name0) {
	NI result0;
	nimfr("parseColor", "colors.nim")
	result0 = (NI)0;
	nimln(391, "colors.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(name0->Sup.len)) raiseIndexError();
		if (!((NU8)(name0->data[((NI) 0)]) == (NU8)(35))) goto LA3;
		nimln(392, "colors.nim");
		result0 = nsuParseHexInt(name0);
	}
	goto LA1;
	LA3: ;
	{
		NI idx0;
		nimln(394, "colors.nim");
		idx0 = binarystrsearch_sfDfYBE9cjkr66pIi04EogQ(T_IeCO5P1bEFfytAeZMzA9bFg_147, 140, name0);
		nimln(395, "colors.nim");
		{
			Valueerror_Gi06FkNeykJn7mrqRZYrkA* e_wz6OCb5PhPVBT32ct43Jmw;
			NimStringDesc* LOC10;
			if (!(idx0 < ((NI) 0))) goto LA8;
			e_wz6OCb5PhPVBT32ct43Jmw = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*)0;
			nimln(2560, "system.nim");
			e_wz6OCb5PhPVBT32ct43Jmw = (Valueerror_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg), sizeof(Valueerror_Gi06FkNeykJn7mrqRZYrkA));
			(*e_wz6OCb5PhPVBT32ct43Jmw).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA);
			nimln(2561, "system.nim");
			nimln(395, "colors.nim");
			LOC10 = (NimStringDesc*)0;
			LOC10 = rawNewString(name0->Sup.len + 15);
appendString(LOC10, ((NimStringDesc*) &T_IeCO5P1bEFfytAeZMzA9bFg_148));
appendString(LOC10, name0);
			asgnRefNoCycle((void**) (&(*e_wz6OCb5PhPVBT32ct43Jmw).Sup.message), LOC10);
			raiseException((Exception*)e_wz6OCb5PhPVBT32ct43Jmw, "ValueError");
		}
		LA8: ;
		nimln(396, "colors.nim");
		if ((NU)(idx0) > (NU)(139)) raiseIndexError();
		result0 = colornames_U7tp4PMw3jdOdV56ZMGhvA[(idx0)- 0].Field1;
	}
	LA1: ;
	popFrame();
	return result0;
}

N_NIMCALL(NIM_BOOL, iscolor_pxBV1VWuv6nVnMvTQgopyg)(NimStringDesc* name0) {
	NIM_BOOL result0;
	nimfr("isColor", "colors.nim")
{	result0 = (NIM_BOOL)0;
	nimln(401, "colors.nim");
	{
		if ((NU)(((NI) 0)) > (NU)(name0->Sup.len)) raiseIndexError();
		if (!((NU8)(name0->data[((NI) 0)]) == (NU8)(35))) goto LA3;
		{
			NI i_ihoalUTodj9cJSsxAUxuE8g;
			NI HEX3Atmp_0TzP5J1AKh9aNy29aydkj9b4A;
			NI T_IeCO5P1bEFfytAeZMzA9bFg_149;
			NI res_2V65MEzYvWxq9bif3Q3VLkg;
			i_ihoalUTodj9cJSsxAUxuE8g = (NI)0;
			HEX3Atmp_0TzP5J1AKh9aNy29aydkj9b4A = (NI)0;
			nimln(402, "colors.nim");
			T_IeCO5P1bEFfytAeZMzA9bFg_149 = subInt((name0 ? name0->Sup.len : 0), ((NI) 1));
			HEX3Atmp_0TzP5J1AKh9aNy29aydkj9b4A = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_149);
			nimln(1908, "system.nim");
			res_2V65MEzYvWxq9bif3Q3VLkg = ((NI) 1);
			{
				nimln(1909, "system.nim");
				while (1) {
					NI T_IeCO5P1bEFfytAeZMzA9bFg_150;
					nimln(1908, "system.nim");
					if (!(res_2V65MEzYvWxq9bif3Q3VLkg <= HEX3Atmp_0TzP5J1AKh9aNy29aydkj9b4A)) goto LA7;
					nimln(1910, "system.nim");
					i_ihoalUTodj9cJSsxAUxuE8g = res_2V65MEzYvWxq9bif3Q3VLkg;
					nimln(403, "colors.nim");
					{
						nimln(1130, "system.nim");
						nimln(403, "colors.nim");
						if ((NU)(i_ihoalUTodj9cJSsxAUxuE8g) > (NU)(name0->Sup.len)) raiseIndexError();
						if (!!((((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) >= ((NU8)(48)) && ((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) <= ((NU8)(57)) || ((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) >= ((NU8)(97)) && ((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) <= ((NU8)(102)) || ((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) >= ((NU8)(65)) && ((NU8)(name0->data[i_ihoalUTodj9cJSsxAUxuE8g])) <= ((NU8)(70))))) goto LA10;
						result0 = NIM_FALSE;
						goto BeforeRet;
					}
					LA10: ;
					nimln(1908, "system.nim");
					T_IeCO5P1bEFfytAeZMzA9bFg_150 = addInt(res_2V65MEzYvWxq9bif3Q3VLkg, ((NI) 1));
					res_2V65MEzYvWxq9bif3Q3VLkg = (NI)(T_IeCO5P1bEFfytAeZMzA9bFg_150);
				} LA7: ;
			}
		}
		nimln(404, "colors.nim");
		result0 = NIM_TRUE;
	}
	goto LA1;
	LA3: ;
	{
		NI LOC13;
		nimln(406, "colors.nim");
		nimln(230, "colors.nim");
		LOC13 = (NI)0;
		LOC13 = binarystrsearch_sfDfYBE9cjkr66pIi04EogQ(T_IeCO5P1bEFfytAeZMzA9bFg_147, 140, name0);
		result0 = (((NI) 0) <= LOC13);
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result0;
}

N_NIMCALL(NI, rgb_s6fKO9c2ZHh9bXQ1gD9as9bwtw)(NI r0, NI g0, NI b0) {
	NI result0;
	nimfr("rgb", "colors.nim")
	result0 = (NI)0;
	nimln(410, "colors.nim");
	nimln(28, "colors.nim");
	nimln(410, "colors.nim");
	result0 = (NI)((NI)((NI)((NU64)(((NI) (r0))) << (NU64)(((NI) 16))) | (NI)((NU64)(((NI) (g0))) << (NU64)(((NI) 8)))) | ((NI) (b0)));
	popFrame();
	return result0;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_colorsInit000)(void) {
	nimfr("colors", "colors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_colorsDatInit000)(void) {
}

